/* ============================================================
   MODULE 17 · RANGE · SWEEP · REVERSAL  (the H/L model, "NY ATM")
   Source: NY ATM teaching guide
============================================================ */
(()=>{
const RANGE_HOURS='7:00–9:30 AM';
const bands=a=>[{t:'band',i0:0,i1:a.open-1,col:COL.lag,a:.06,text:'range window 7:00–9:30'},{t:'band',i0:a.open,i1:a.open+5,col:COL.ok,a:.07,text:'first 30 min'},{t:'vline',i:a.open,col:COL.ice,text:'9:30 open'}];
const rangeLines=a=>[hlAt(a.RH,'range high',COL.ok,0,{scale:true}),hlAt(a.RL,'range low',COL.bad,0,{scale:true})];
const aD0=r=>{const a=atmScn(r,{side:pick(r,['low','high']),trigger:pick(r,['ifvg','mss']),early:r()<.5});
  return{kind:'level',topic:'Step 1 · Define the range',q:`The shaded band is the range window (7:00–9:30 AM). Place a line at the RANGE HIGH and another at the RANGE LOW formed inside it.`,C:a.C.slice(0,a.open+2),t0:a.t0,ov:bands(a),truth:[{p:a.RH,tol:Math.max(1.1,a.s*.6),label:'range high'},{p:a.RL,tol:Math.max(1.1,a.s*.6),label:'range low'}],
   why:`The range high (${fm(a.RH)}) and range low (${fm(a.RL)}) are the highest high and lowest low formed during the window. Mark both before the execution window begins: everything else is built around these two levels.`}};
const aD1=r=>{const a=atmScn(r,{side:pick(r,['low','high']),trigger:pick(r,['ifvg','mss']),early:r()<.5}),lo=a.side==='low';
  return{kind:'tap',many:false,topic:'Step 3 · The sweep',q:`The range levels are marked. Click the candle that SWEEPS one side of the range: the first to trade through it during the execution window.`,C:a.C,t0:a.t0,ov:[...bands(a),...rangeLines(a)],want:[a.sweepI],
   why:`The candle at ${hhmm(a.t0+a.sweepI*5)} trades through the range ${lo?'low':'high'} (${fm(lo?a.RL:a.RH)}), running the ${lo?'sell':'buy'} orders resting there. That sets the bias: look for a reversal back toward the other side.`}};
const aD2=r=>{const trig=pick(r,['ifvg','mss']),a=atmScn(r,{side:pick(r,['low','high']),trigger:trig,early:r()<.5}),lo=a.side==='low',ifv=trig==='ifvg';
  const i=ifv?a.entryI:a.mssI;
  return{kind:'tap',many:false,topic:'Step 4 · The entry trigger',q:ifv?`After the sweep, a fair value gap formed on the move and price then closed back through it (an inversion). Click the candle that CLOSES through that gap: the inversion fair value gap trigger.`:`After the sweep, price breaks a recent swing point to confirm the reversal. Click the candle that closes ${lo?'above':'below'} the swing ${lo?'high':'low'} (marked): the market structure shift.`,C:a.C,t0:a.t0,ov:[...bands(a),...rangeLines(a),...(ifv?[rectAt(a.zone.i0,a.zone.i2,a.zone.lo,a.zone.hi,'FVG',COL.lag,{dash:true})]:[hlAt(a.swingHigh.p,'swing '+(lo?'high':'low'),COL.gold,a.swingHigh.i,{scale:true})])],want:[i],
   why:ifv?`The candle at ${hhmm(a.t0+i*5)} closes ${lo?'above':'below'} the gap left by the sweep leg (${fm(a.zone.lo)}–${fm(a.zone.hi)}): the gap flips and now acts as ${lo?'support':'resistance'}. Enter on that candle close.`:`The candle at ${hhmm(a.t0+i*5)} closes ${lo?'above':'below'} ${fm(a.swingHigh.p)}, confirming the reversal in structure, and leaves a fair value gap behind it as the entry zone.`}};
const aD3=r=>{const trig=pick(r,['ifvg','mss']),a=atmScn(r,{side:pick(r,['low','high']),trigger:trig,early:r()<.5});
  return{kind:'rect',topic:'The fair value gap',q:trig==='ifvg'?'Mark the fair value gap that the sweep leg left behind, the gap that later gets inverted.':'Mark the fair value gap left behind by the break of structure: the entry zone.',C:a.C.slice(0,a.entryI+2),t0:a.t0,ov:[...bands(a),...rangeLines(a)],truth:[{i0:a.zone.i0,i1:a.zone.i2,lo:a.zone.lo,hi:a.zone.hi}],
   why:`The gap spans ${fm(a.zone.lo)}–${fm(a.zone.hi)}, between candle 1's wick and candle 3's wick (Module 6). ${trig==='ifvg'?'When price closes back through it, it becomes the inversion fair value gap trigger.':'It is the entry zone left behind by the break.'}`}};
const aD4=r=>{const a=atmScn(r,{side:pick(r,['low','high']),trigger:pick(r,['ifvg','mss']),early:r()<.5}),lo=a.side==='low';
  return{kind:'level',topic:'Stop and target',q:`Price has swept the range ${lo?'low':'high'} and the entry has triggered. Place the STOP at the swept extreme and the TARGET at the opposite side of the range.`,C:a.C.slice(0,a.entryI+3),t0:a.t0,ov:[...bands(a),...rangeLines(a)],truth:[{p:a.stop,tol:Math.max(1.1,a.s*.55),label:'stop (swept extreme)'},{p:a.target,tol:Math.max(1.1,a.s*.6),label:'target (opposite side)'}],
   why:`The stop sits at the swept extreme (${fm(a.stop)}). The default target is the other side of the range: since the ${lo?'low':'high'} was swept, target the range ${lo?'high':'low'} at ${fm(a.target)}. (The stop can alternatively sit at the inversion gap itself: both are valid.)`}};
const aD5=r=>{const a=atmScn(r,{side:pick(r,['low','high']),trigger:'ifvg',early:true}),lo=a.side==='low';
  const o=lo?['Look long: a reversal entry back toward the range high','Look short: the break lower will continue','No bias until both sides are swept','Fade the range high immediately']:['Look short: a reversal entry back toward the range low','Look long: the break higher will continue','No bias until both sides are swept','Buy the range low immediately'];
  return{kind:'mcq',topic:'Step 3 · Bias from the sweep',q:`Price sweeps the range ${lo?'LOW':'HIGH'} during the execution window. What does that set?`,o,C:a.C.slice(0,a.sweepI+2),t0:a.t0,ov:[...bands(a),...rangeLines(a)],
   why:`Range ${lo?'LOW':'HIGH'} gets swept → look for a reversal entry back toward the range ${lo?'HIGH':'LOW'}. The sweep sets the bias.`}};
const aD6=r=>{const a=atmScn(r,{side:pick(r,['low','high']),trigger:pick(r,['ifvg','mss']),early:r()<.5}),sw=hhmm(a.t0+a.sweepI*5),en=hhmm(a.t0+a.entryI*5),ap=a.aplus;
  return{kind:'mcq',topic:'Grading the setup',q:`The execution window opens at 9:30. The sweep happens at ${sw} and the entry trigger completes at ${en}. How is this setup graded?`,o:ap?['A+: the sweep and entry complete within the first 30 minutes of the window','A lower-quality version: it came too late','Not valid','No trade']:['A valid but lower-quality (later) version: it did not complete in the first 30 minutes','A+: any valid sweep is A+','Not valid at all','No trade: it is too late'],C:a.C,t0:a.t0,ov:[...bands(a),...rangeLines(a)],
   why:ap?'A sweep-and-entry that completes within the first 30 minutes of the execution window is graded as the highest-quality version of this setup: A+.':'The setup is still valid, but it completed after the first 30 minutes of the window, so it is not the highest-quality (A+) version.'}};
const aD7=r=>{const a=atmScn(r,{sweep:false,side:pick(r,['low','high'])});
  return{kind:'mcq',topic:'The no-trade rule',q:'The execution window has reached its cutoff time (marked) and neither the range high nor the range low has been swept. What does the model say?',o:['No trade: that session is simply a no-trade, and following that rule keeps you out of a bad day','Take the best-looking move anyway','Trade the range breakout','Wait for the next day\'s range'],C:a.C,t0:a.t0,ov:[...bands(a),...rangeLines(a),{t:'vline',i:a.cut,col:COL.gold,text:'cutoff'}],
   why:'If the cutoff arrives and neither side of the range was swept, the model did not trigger: stop looking for it. Walking away is a form of following the rules, not a failure to find a trade.'}};
const POOL=[
 ['A high-impact news day is scheduled (for example the day before NFP). What does the model say?',['Sit the day out entirely, however the setup looks','Trade it with double size','Only trade the sweep','Take the lunch window only'],'Avoid trading this model around major scheduled news. The day before NFP is explicitly called out as a day to sit out.'],
 ['The trade has run to about 5R but not all the way to the target. What does the guide say about partials?',['Taking something off along the way is normal and healthy: don\'t give back a good trade insisting on the last point','Never take partials','Always hold for the full target','Close everything immediately'],'Not every trade reaches the full target. Take something off along the way.'],
 ['Which statement about the two entry triggers is correct?',['Both are valid: neither is described as superior, just different flavours of the same confirmation','The inversion FVG is always better','The structure shift is always better','You must use both together'],'Teach both and pick whichever you are more comfortable reading.'],
 ['Where can the stop-loss go?',['At the swept extreme, or at the inversion fair value gap itself: both are valid','Only at the range midpoint','Only at the target','Anywhere'],'Presented as valid, interchangeable options.'],
 ['What is the default target?',['The opposite side of the range','Twice the stop','The previous week\'s high','A round number'],'Low swept → target the range high, and vice versa.']];
const aD8=r=>{const p=pick(r,POOL);return mcq('Discipline',p[0],p[1],p[2])};
const windowsTbl=tblx(['Session','Range window','Execution window'],[['Morning / pre-market','Pre-market range (roughly 7:00–9:30 AM) marks the AM range high/low','From the open, looking for the sweep-and-reversal shortly after'],['Lunch','Late-morning / midday range (roughly 11:30 AM–1:30 PM)','Roughly 1:30–3:00 PM, with a 3:00 PM cutoff if no sweep'],['PM','Often built from the same lunch high/low already marked','Afternoon window following lunch: same sweep-then-reversal logic']]);
MODS.push({id:'m17',ph:6,chart:true,t:'Range, Sweep, Reversal (H/L · NY ATM)',out:'Mark a range, wait for a sweep, then take the reversal back to the other side.',flag:'Strategy model',
 ls:['The model in one sentence','Step 1: define the range','Step 2: the execution window and cutoff','Step 3: wait for the sweep','Step 4: two valid entry triggers','Stop, target, grading and partials','The three daily windows','Discipline rules'],
 task:'Pick one of the three session windows to start with and mark its range high and low every day, logging whether a sweep happened and on which side. For each logged day note which entry trigger appeared (inversion FVG or structure shift + FVG) and which time frame gave the cleanest entry. Track how often the no-trade outcome occurs versus a valid sweep and reversal. Practise grading each trade A+ (first 30 minutes) versus a later entry, and journal every trade with the session window, range levels, trigger used, stop placement and final R multiple.',
 ex:()=>atmScn(rr(111),{side:'low',trigger:'ifvg',early:true}),
 learn:[
  {t:'The model in one sentence',h:key('<p><b>Identify a range high and a range low. Wait for a sweep of one side of that range. Then look for a reversal entry back toward the other side.</b></p>','The whole model')+`<p>It is a simple framework, and you get three separate chances to look for it every day, one in each session window.</p>`},
  {t:'Key terms',h:tblx(['Term','Meaning'],[['ATM approach','A range-sweep-and-reversal model: mark a range\'s high and low from a defined window, then wait for one side to be swept before looking for a reversal entry the other way'],['Range high / range low','The highest high and lowest low formed during a specific, pre-defined time window (different windows for different sessions)'],['Execution window','The block of time AFTER the range is formed in which you are allowed to look for the sweep and take an entry. Outside it, the setup is off'],['Sweep','Price trading through the range high or low, running the liquidity resting there: the trigger that shifts attention to a reversal entry on the opposite side'],['Inversion fair value gap (IFVG)','A fair value gap that gets broken and flips to act as support/resistance in the new direction. One of the two valid entry triggers'],['Market structure shift (MSS) + fair value gap','The second valid trigger: a break of a recent swing point confirming the reversal, combined with a fresh fair value gap left behind by that break'],['No-trade rule / cutoff time','If neither the range high nor the range low has been swept by the end of the execution window, the session is a no-trade']])},
  {t:'Step 1 · Define the range',h:`<p>The range window is different for each of the three daily sessions (see the table below), but the process is always the same: mark the <b>highest high and lowest low formed during that specific window</b>.</p><p>Physically mark both the range high and the range low on the chart <b>before the execution window begins</b>. They become the two levels everything else is built around.</p>`},
  {t:'Step 2 · The execution window and cutoff',h:`<p>Each session has its own execution window that follows its range window. It is the only period during which a sweep-and-entry is valid.</p>${warn('<p>If the cutoff time arrives and neither the range high nor the range low has been swept, the model did not trigger. <b>Stop looking for it.</b> That session is simply a no-trade. Following that one rule alone would have kept you out of a bad day.</p>','The no-trade rule')}`},
  {t:'Step 3 · Wait for the sweep',h:`<p>Inside the execution window, your only job is to watch for price to trade through either the range high or the range low, running the resting liquidity there. Then note <b>which side got swept</b>: that sets the bias.</p>${tblx(['If this is swept…','Look for…'],[['Range LOW','A reversal entry back toward the range HIGH'],['Range HIGH','A reversal entry back toward the range LOW']])}`},
  {t:'Step 4 · Entry: two valid triggers',h:`<p>Learn both and use whichever you read more comfortably. Neither is described as superior: they are different flavours of the same confirmation.</p><ul><li><b>Option A · Inversion fair value gap (IFVG):</b> after the sweep, wait for a fair value gap to form and then get broken (inverted) in the reversal direction. Enter on the candle close confirming the inversion.</li><li><b>Option B · Market structure shift + FVG:</b> wait for price to break a recent swing point (confirming the reversal in structure) and use the fair value gap left behind by that break as the entry zone.</li></ul><p><b>Stop-loss:</b> at the swept extreme (the range high or low that got taken out), or at the inversion fair value gap itself. Both are presented as valid, interchangeable options.</p>`},
  {t:'Grading setups and setting targets',h:`<ul><li><b>Quality tiering.</b> A sweep-and-entry that completes within the <b>first 30 minutes</b> of the execution window is graded as the highest-quality version: <b>A+</b>.</li><li><b>Target.</b> The default target is simply the <b>other side of the range</b>: if the low was swept, target the range high, and vice versa.</li><li><b>Realistic expectations.</b> Not every trade reaches the full target. Partial profit-taking is a normal, healthy part of managing these trades. A trade can still run to around 5.5 risk-to-reward without hitting the full target: take something off along the way. Don't be the trader who insists on squeezing out one extra point and gives back a good trade.</li></ul>`},
  {t:'The three daily session windows',h:windowsTbl+`<p class="muted" style="font-size:13px">Treat these clock times as the framework to verify through your own back-testing, not a substitute for confirming them yourself. The same range-and-sweep logic transfers beyond New York day sessions: it works during the Asia session and morning sessions too.</p>`},
  {t:'Discipline rules',h:`<ol><li><b>Skip known high-impact news days.</b> For example, the day before NFP is a day to sit out entirely, regardless of how the setup looks.</li><li><b>Respect the no-trade outcome.</b> If the cutoff passes with no sweep on either side, that IS the correct outcome for the day, not a setup to force. Walking away is a form of following the rules.</li><li><b>Don't hold out for the last point.</b> Demanding the absolute maximum out of every trade turns good trades into worse ones. Take something off along the way.</li></ol>`},
  {t:'The cheat sheet',h:`<ol><li>Mark the range high and low for the session window being traded.</li><li>Know the execution window and its cutoff time before the range window even closes.</li><li>Wait for a sweep of either side: that sets your reversal bias.</li><li>Enter on either an inversion FVG <b>or</b> a market structure shift + FVG.</li><li>Stop-loss at the swept extreme or at the inversion fair value gap.</li><li>Target the opposite side of the range as the default.</li><li>A setup that completes within the first 30 minutes of the execution window is the highest quality: grade it A+.</li><li>If the cutoff passes with no sweep, that is a valid no-trade. Stop looking.</li><li>Skip known high-impact news days entirely.</li><li>Take partials along the way. Don't demand the full target on every trade.</li></ol>`}
 ],
 recall:rc('Module 8','What is an inverse fair value gap?',['A fair value gap that gets closed through (disrespected) within the trend it was supposed to support','A gap that has filled to 50%','Any gap at the open','A bearish gap on a higher time frame'],'It is one of this model\'s two valid triggers.'),
 see:a=>{const C=a.C,mssA=atmScn(rr(112),{side:'low',trigger:'mss',early:true}),late=atmScn(rr(113),{side:'high',trigger:'ifvg',early:false}),none=atmScn(rr(114),{sweep:false,side:'low'});return[
  {focus:a.open-14,ov:[...bands(a).slice(0,1),...rangeLines(a)],cap:`<b>Step 1 · The range.</b> During the range window (7:00–9:30 AM) price builds a high at <b>${fm(a.RH)}</b> and a low at <b>${fm(a.RL)}</b>. Mark both before the execution window begins.`},
  {focus:a.open+3,ov:[...bands(a),...rangeLines(a)],cap:'<b>Step 2 · The execution window.</b> From the open, you are allowed to look for a sweep and an entry. The first 30 minutes (shaded green) is where the highest-quality setups come.'},
  {focus:a.sweepI,ov:[...bands(a),...rangeLines(a),boxOf(C,a.sweepI,a.sweepI,COL.sig,.5),tagAt(a.sweepI,C[a.sweepI].l,'sweeps the range low','below',COL.sig)],cap:`<b>Step 3 · The sweep.</b> At ${hhmm(a.t0+a.sweepI*5)} price trades through the range <b>low</b>, running the sell orders resting there. That sets the bias: look for a reversal back toward the range <b>high</b>.`},
  {focus:a.entryI,ov:[...bands(a),...rangeLines(a),rectAt(a.zone.i0,a.zone.i2,a.zone.lo,a.zone.hi,'bearish FVG from the sweep leg',COL.lag,{dash:true})],cap:'<b>Step 4 · Option A: the inversion FVG.</b> The move down left a bearish fair value gap. Wait for it to be broken in the reversal direction.'},
  {focus:a.entryI,ov:[...bands(a),...rangeLines(a),rectAt(a.zone.i0,a.zone.i2,a.zone.lo,a.zone.hi,'inverted FVG',COL.lag,{dash:true}),boxOf(C,a.entryI,a.entryI,COL.sig,.5),tagAt(a.entryI,C[a.entryI].c,'ENTRY: close above the gap','above',COL.sig)],cap:`<b>Enter on the candle close that confirms the inversion.</b> This candle closes above the gap: it has flipped. Entry about <b>${fm(a.entry)}</b>.`},
  {focus:a.entryI+2,ov:[...bands(a),hlAt(a.RH,'target: range high',COL.ok,0),hlAt(a.stop,'stop: swept extreme',COL.bad,0),hlAt(a.entry,'entry',COL.sig,a.entryI-4)],cap:`<b>Stop and target.</b> The stop goes at the swept extreme (${fm(a.stop)}) or at the inversion gap. The default target is the other side of the range: ${fm(a.target)}.`},
  {sc:mssA,focus:mssA.entryI,ov:[...bands(mssA),...rangeLines(mssA),hlAt(mssA.swingHigh.p,'swing high',COL.gold,mssA.swingHigh.i,{scale:true}),boxOf(mssA.C,mssA.mssI,mssA.mssI,COL.sig,.5),tagAt(mssA.mssI,mssA.C[mssA.mssI].c,'MSS: closes above swing high','above',COL.sig),rectAt(mssA.zone.i0,mssA.zone.i2,mssA.zone.lo,mssA.zone.hi,'FVG: entry zone',COL.lag,{dash:true})],cap:'<b>Option B: market structure shift + FVG.</b> After the sweep, price breaks a recent swing high, confirming the reversal in structure, and leaves a fair value gap behind as the entry zone. Neither option is superior.'},
  {sc:late,focus:late.entryI,ov:[...bands(late),...rangeLines(late),boxOf(late.C,late.sweepI,late.sweepI,COL.gold,.5),tagAt(late.sweepI,late.C[late.sweepI].h,'later than the first 30 min','above',COL.gold)],cap:'<b>Grading.</b> This sweep and entry came well after the first 30 minutes of the window. It is still a valid setup, but it is not the A+ version.'},
  {sc:none,focus:none.cut-6,ov:[...bands(none),...rangeLines(none),{t:'vline',i:none.cut,col:COL.gold,text:'cutoff'}],cap:'<b>The no-trade day.</b> Price stayed inside the range all the way to the cutoff. Neither side was swept, so the model never triggered: this session is a no-trade. Walking away is following the rules.'}]},
 sum:a=>({ov:[...bands(a),...rangeLines(a),tagAt(a.sweepI,a.C[a.sweepI].l,'sweep','below',COL.sig),tagAt(a.entryI,a.C[a.entryI].c,'entry','above',COL.ok)]}),
 explain:{prompts:['Explain the model in your own words, from marking the range to the target, including what happens when no side is swept.','Describe the two valid entry triggers, where the stop goes, how an A+ setup is defined, and how you should treat partials.'],
  ideas:['Mark the range high and low from the session\'s defined window, before the execution window opens','The execution window is the only time a sweep-and-entry is valid','Wait for a sweep of one side: that sets the bias','Range low swept → reversal toward the range high (and vice versa)','Two valid triggers: an inversion FVG, or a market structure shift plus FVG','Stop at the swept extreme or at the inversion fair value gap','Default target is the opposite side of the range; first 30 minutes of the window is A+','No sweep by the cutoff is a no-trade; skip news days; take partials']},
 drills:[aD0,aD1,aD2,aD3,aD4,aD5,aD6,aD7,aD8],
 bank:[
  mcq('Model','Which is the one-sentence model?',['Identify a range high and low, wait for a sweep of one side, then look for a reversal entry toward the other side','Buy every breakout of the range','Trade inside the range','Fade every new high'],'Range, sweep, reversal.'),
  mcq('Range','The range high and low are…',['The highest high and lowest low formed during a specific, pre-defined time window','The previous day\'s high and low','The all-time high and low','The opening price'],'Different windows are used for different sessions.'),
  mcq('Range','When must you mark the range high and low?',['Before the execution window begins','After the entry','At the end of the day','Only after a sweep'],'They are the two levels everything else is built around.'),
  mcq('Window','What is the execution window?',['The block of time after the range is formed in which you may look for the sweep and take an entry','The range window itself','The whole day','Overnight'],'Outside it, the setup is off.'),
  mcq('Window','The cutoff time arrives with no sweep of either side. What does that mean?',['A no-trade for that session','A reason to force an entry','The range is invalid','Wait for tomorrow\'s range'],'Stop looking for the setup.'),
  mcq('Sweep','The range LOW gets swept. Where do you look for a reversal entry?',['Back toward the range high','Further below the low','Sideways','Nowhere'],'Low swept → reversal toward the high.'),
  mcq('Sweep','The range HIGH gets swept. Where do you look for a reversal entry?',['Back toward the range low','Further above the high','Sideways','Nowhere'],'High swept → reversal toward the low.'),
  mcq('Entry','Which are the two valid entry triggers?',['An inversion fair value gap, or a market structure shift plus a fair value gap','A moving average cross or RSI','Any green candle','A news release or a gap fill'],'Neither is superior.'),
  mcq('Entry','For the inversion FVG trigger, when do you enter?',['On the candle close that confirms the inversion','At the first touch of the gap','Before the sweep','At the target'],'Wait for the close.'),
  mcq('Stop & target','Where can the stop-loss go?',['At the swept extreme, or at the inversion fair value gap itself','At the target','At the range midpoint only','At the open'],'Both are valid.'),
  mcq('Stop & target','What is the default target?',['The opposite side of the range','Double the stop','The previous day\'s close','The round number above'],'If the low was swept, target the range high.'),
  mcq('Grading','What makes a setup A+?',['The sweep and entry complete within the first 30 minutes of the execution window','A very large candle','A news release','A sweep of both sides'],'The highest-quality version.'),
  mcq('Expectations','A trade runs most of the way to the target. What does the guide say?',['Take partials along the way: don\'t insist on the last point','Never take partials','Add to the trade','Move the stop to the entry only'],'Partial profit-taking is normal and healthy.'),
  mcq('Windows','The morning range window is roughly…',['7:00–9:30 AM (the pre-market)','9:30–10:00 AM','11:30 AM–1:30 PM','3:00–4:00 PM'],'The execution window runs from the open.'),
  mcq('Windows','The lunch execution window runs roughly…',['1:30–3:00 PM, with a 3:00 PM cutoff if no sweep','9:30–10:30 AM','7:00–9:30 AM','4:00–5:00 PM'],'The lunch range is roughly 11:30 AM–1:30 PM.'),
  mcq('Windows','Where does the PM window\'s range often come from?',['The same lunch high and low already marked','The pre-market range','The previous week','A new indicator'],'Same sweep-then-reversal logic.'),
  mcq('Discipline','What does the guide say about the day before NFP?',['Sit it out entirely, regardless of the setup','Trade it with extra size','Trade only the lunch window','It is the best day'],'Skip known high-impact news days.')
 ],
 exam:{bank:4,gen:[[0,1],[1,1],[2,1],[3,1],[4,1],[5,1],[6,1],[7,1]]},examDesc:'Marking the range, the sweep, both entry triggers, stop and target, A+ grading, and the no-trade rule, on charts.'});
})();

/* ============================================================
   MODULE 18 · AMD / PO3  (accumulation · manipulation · distribution)
   Source: AMD / PO3 teaching guide
============================================================ */
(()=>{
const accRect=r=>{const a=amdScn(r,{htf:pick(r,['up','down']),brk:'against'});
  return{kind:'rect',topic:'Accumulation',q:'Mark the ACCUMULATION: the range-bound, choppy phase where price consolidates sideways. Drag across the range from its high to its low.',C:a.C,truth:[{i0:a.acc.i0,i1:a.acc.i1,lo:a.acc.lo,hi:a.acc.hi}],minIoU:.45,
   why:`Price chopped sideways between ${fm(a.acc.lo)} and ${fm(a.acc.hi)} for about ${a.acc.i1-a.acc.i0+1} candles. This is the no-trade zone: entering here almost always leads to being chopped around.`}};
const manTap=r=>{const a=amdScn(r,{htf:pick(r,['up','down']),brk:'against'}),idx=[];for(let i=a.man[0];i<=a.man[1];i++)idx.push(i);const down=a.htf==='up';
  return{kind:'tap',many:true,topic:'Manipulation',q:`The higher-time-frame trend is ${a.htf}. Select every candle of the MANIPULATION: the deliberate-looking move that pushes through the ${down?'low':'high'} of the accumulation range, against the trend, to sweep liquidity.`,C:a.C,ov:[hlAt(down?a.acc.lo:a.acc.hi,'accumulation '+(down?'low':'high'),COL.ice,a.acc.i0,{scale:true})],want:idx,
   why:`These candles push ${down?'below':'above'} the accumulation range, sweeping the orders resting there: stop-losses of people already positioned and breakout orders. It looks directional but it's the trap, designed to fuel the opposite move.`}};
const classify=r=>{const htf=pick(r,['up','down']),brk=pick(r,['against','with']),a=amdScn(r,{htf,brk}),dirBreak=(htf==='up')===(brk==='with')?'upside':'downside',man=brk==='against';
  const O=man?['Manipulation: a trap against the higher-time-frame trend, so look for distribution in the trend\'s direction','Distribution: the real move, so keep going in the breakout direction','Accumulation: keep waiting inside the range','No read is possible']:['Distribution: the real move, going with the higher-time-frame trend','Manipulation: a trap, so fade it','Accumulation: still ranging','No read is possible'];
  return{kind:'mcq',topic:'The mistake: manipulation vs confirmation',q:`The higher-time-frame trend is ${htf}. Price has just broken out of the accumulation range to the ${dirBreak}. Is this distribution, or the manipulation designed to trap people who think it's distribution?`,o:O,C:a.C.slice(0,a.cut),ov:[rectAt(a.acc.i0,a.acc.i1,a.acc.lo,a.acc.hi,'accumulation',COL.lag,{dash:true,ext:false})],
   why:man?`The breakout is ${dirBreak==='downside'?'down':'up'}, against the ${htf}trend. The natural instinct, "we broke the range so it will keep going", is exactly backwards during manipulation. Check it against the higher-time-frame trend: it points the other way, so treat the break as a trap being set.`:`The breakout is in the direction of the ${htf}trend, so this is the real move (distribution), the kind aligned with the higher-time-frame trend that actually pays.`}};
const obTap=r=>{const a=amdScn(r,{htf:pick(r,['up','down']),brk:'against'}),i=a.man[1];
  return{kind:'tap',many:false,topic:'Order block',q:'Click the ORDER BLOCK: the last candle in the opposite direction before the strong directional move (the distribution) began.',C:a.C,ov:[boxOf(a.C,a.dist0,a.C.length-1,COL.ok,1)],want:[i],
   why:`The last candle moving against the strong move before it began is the order block (${hhmm(510+i*5)}). When price returns to it and respects it, that adds confidence to the distribution move.`}};
const PH_ITEMS=[[0,['Price chops sideways in a tight range','Entering here "because it looks like it\'s about to break out"','A no-trade zone: no directional edge yet']],[1,['A sharp move through one edge of the range that sweeps the liquidity there','The trap: it looks directional but fuels the opposite move','The move that sweeps stop-losses and breakout orders']],[2,['The real, intended directional move','Price moves in its true direction after liquidity is cleared','The phase that actually delivers profit']]];
const sortPh=r=>({kind:'sort',topic:'Three phases',q:'Which phase does each description belong to?',buckets:['Accumulation','Manipulation','Distribution'],items:shuf(PH_ITEMS.map(([b,ds])=>({t:pick(r,ds),b})),r),why:'Accumulation is the no-trade chop. Manipulation is the trap. Distribution is the real move that pays, ideally with the higher-time-frame trend.'});
const CONF=[['A bullish fair value gap with a swing low sitting inside it','Fair value gap + swing point: a stronger draw on liquidity than a plain FVG'],['Price fails to close outside or through the fair value gap','Gap not closed through: the market wants to continue in the gap\'s direction'],['The setup lines up with 9:30 AM Eastern, the New York Stock Exchange open','Key session time ("macro"): extra weight simply for the timing'],['Obvious equal highs or equal lows sitting beyond price','Equal highs / equal lows: a clear draw once distribution begins'],['Price returns to an order block during manipulation and reacts from it','Order block respected: adds confidence to the distribution move that follows']];
const confQ=r=>{const [d,a]=pick(r,CONF),others=CONF.filter(x=>x[1]!==a).map(x=>x[1]);return mcq('Confluences',`Which confluence is this? "${d}."`,[a,...shuf(others,r).slice(0,3)],'These stack on top of the AMD structure before a setup is treated as high quality. The AMD structure itself is the foundation.')};
MODS.push({id:'m18',ph:6,chart:true,t:'AMD / PO3: Accumulation, Manipulation, Distribution',out:'Read every move as a range, a trap and the real move.',flag:'Strategy model',
 ls:['A structure, not a setup: fractal, on any timeframe and any asset','The three phases one at a time','The #1 rule: trade with the trend','The confluence checklist','Worked trade examples','The mistake students make most'],
 task:'Mark up 10 charts (any asset, any time frame) and label the accumulation, manipulation and distribution phase on each. For each marked chart, note whether the distribution phase aligned with the higher-time-frame trend or fought it, and compare the win rate of the two. Practise spotting fair value gaps with a swing point inside them. Keep a running list of the key session "macro" times for the assets you trade (for example the 9:30 AM New York open) and note how often AMD sequences line up with them. Journal every trade with the phase the entry was taken in, which confluences were present, and whether it went with or against the higher-time-frame trend.',
 ex:()=>amdScn(rr(121),{htf:'up',brk:'against'}),
 learn:[
  {t:'Key terms',h:tblx(['Term','Meaning'],[['AMD / PO3','Accumulation, Manipulation, Distribution, also called Power of Three. The three phases every price move cycles through; the backbone of this module'],['Accumulation','A range-bound, choppy phase where price consolidates sideways. A no-trade zone: entering here almost always leads to being chopped around'],['Manipulation','A deliberate-looking move (a stop hunt / liquidity sweep) that pushes price through the edge of the accumulation range in the OPPOSITE direction of the real move to come. Its job is to trap early traders and fuel the real move'],['Distribution','The real, intended directional move that follows manipulation: the phase that actually pays'],['Liquidity','Clusters of resting stop-losses and pending orders (above old highs, below old lows) that price is drawn toward and often runs through during manipulation'],['Draw on liquidity','The specific level or zone price is being pulled toward: equal highs/lows, a fair value gap, or a swing point. Supporting evidence a move has room to run'],['Fair value gap / "BISI"','A 3-candle imbalance showing aggressive one-sided movement. A bullish FVG (sometimes called a BISI: Buyside Imbalance, Sellside Inefficiency) with a swing low inside it is an especially strong draw on liquidity'],['Order block','The last candle in the opposite direction before a strong directional move. When price returns to it and "respects" it, that adds confidence to the distribution move'],['Macro / key session time','A specific clock time (for example 9:30 AM Eastern, the New York Stock Exchange open) where price behaviour is given extra weight simply because of the time of day'],['Inversion FVG (IFVG)','A fair value gap that gets broken and starts acting as support/resistance in the opposite direction. Can be used as a lower-time-frame entry trigger once AMD structure is identified']])},
  {t:'A structure, not a setup',h:`<p>AMD isn't one specific trade trigger. It is a repeating pattern that shows up inside every candle, every session and every trend. Treat it as a <b>lens you look through</b>, not a checklist you tick once. It is the "operating system" behind almost every other setup.</p><ul><li><b>Any timeframe.</b> It plays out identically on a 30-second chart, a 1-minute, 5-minute, hourly or 5-hour chart. It is <b>fractal</b>: the same three phases repeat at every zoom level, only the scale changes. (Press <b>15m</b> in the chart bar to see the same structure at a different scale.)</li><li><b>Any asset.</b> Bitcoin, stocks, crypto, forex, indices. It is rooted in how liquidity behaves, not in any one market's rules.</li></ul>`},
  {t:'Phase 1 · Accumulation: the no-trade zone',h:`<p>Price chops sideways in a range. This is the phase students most want to jump into (because it "looks like it's about to break out") and the phase they most need to avoid.</p>${warn('<p><b>Do not enter during accumulation.</b> You will get chopped up, and you are entering too early: there is no directional edge yet.</p>','Rule')}`},
  {t:'Phase 2 · Manipulation: the trap',h:`<p>Price makes a sharp move through one edge of the accumulation range, sweeping the liquidity sitting there (the stop-losses of people already positioned, or the breakout orders of people entering the range). This move <b>looks</b> directional, but it is designed to fuel the <b>opposite</b> move.</p><p class="muted"><i>"We get a manipulation lower, which is taking out all of that accumulation, and that is hopefully going to fuel our move higher. Don't mistake this for the real move: it's the trap, not the trade."</i></p>`},
  {t:'Phase 3 · Distribution: the real move',h:`<p>After manipulation clears out the liquidity, price moves in its true intended direction. This is the phase that actually delivers profit, and ideally it is the phase that aligns with the higher-time-frame trend.</p>`},
  {t:'The #1 rule: trade with the trend',h:`<p>This is the single biggest edge multiplier. If the higher time frame is already trending up, look for AMD sequences where <b>manipulation sweeps to the downside</b> and <b>distribution continues the uptrend</b>, not the reverse. You are not fighting the big bulls or bears.</p>${warn('<p>The natural instinct, "we broke the range, so we must keep going that direction", is <b>exactly backwards during manipulation</b>. When price breaks out of accumulation to the downside, it <i>feels</i> like confirmation that price will keep falling. See it as an early-seller trap being set. This is the most common way this concept is misread.</p>','The most common mistake')}<p>Be honest with yourself: a small scalp in the direction of the manipulation leg (counter-trend) can technically be a valid trade. Treat it as the <b>lower-quality option</b>, with going with the trend as the standard you default to.</p>`},
  {t:'The confluence checklist',h:`<p>AMD structure alone is the foundation, but stack these confluences on top before treating a setup as high quality.</p>${tblx(['Confluence','What to look for'],[['Fair value gap + swing point','A bullish FVG with a swing low sitting inside it is a stronger draw on liquidity than a plain FVG'],['Gap not closed through','If price fails to close outside/through the fair value gap, it is a sign the market wants to continue in the gap\'s direction'],['Key session time ("macro")','A setup that lines up with a known key time, such as 9:30 AM Eastern, gets extra weight simply for the timing'],['Equal highs / equal lows','Obvious liquidity pools above/below price that serve as a clear draw once distribution begins'],['Order block respected','If price returns to an order block during manipulation and reacts from it, that adds confidence to the distribution move that follows']])}${key('<p>There is <b>no single fixed entry trigger</b> taught here: the emphasis is on recognising the AMD structure itself first. Once recognised, a lower-time-frame inversion FVG can be used as a precise entry trigger during the distribution phase, but treat that as optional refinement, not a requirement.</p>','Teaching note')}`},
  {t:'Worked example 1 · Bullish AMD with FVG and macro time',h:`<ul><li><b>Higher-time-frame context:</b> already in an uptrend, so the setup continues that trend rather than fighting it.</li><li><b>Accumulation:</b> price ranges sideways: a no-trade zone.</li><li><b>Manipulation:</b> price sweeps lower, taking out the accumulation range's liquidity.</li><li><b>Confluence 1:</b> a 1-minute bullish fair value gap with a swing low inside it, a strong draw on liquidity.</li><li><b>Confluence 2:</b> price did not close outside that fair value gap, reinforcing that the market wanted to continue higher.</li><li><b>Confluence 3:</b> the setup lined up with 9:30 AM Eastern, the New York Stock Exchange open: a key "macro" moment.</li><li><b>Confluence 4:</b> equal highs above price acted as the draw on liquidity for the distribution leg.</li><li><b>Distribution:</b> price moves higher, continuing the existing uptrend and confirming the AMD read.</li></ul>`},
  {t:'Worked example 2 · Bullish AMD with order block respect',h:`<ul><li><b>Higher-time-frame context:</b> another bullish uptrend environment.</li><li><b>Accumulation:</b> price stalls sideways once again.</li><li><b>Manipulation:</b> price sweeps out multiple lows and respects an order block on the way down.</li><li><b>Distribution:</b> a strong move higher follows, continuing the trend.</li><li><b>Teaching point:</b> a small counter-trend scalp short was technically available at the manipulation low, but the higher-quality trade was staying aligned with the uptrend and taking the long distribution move.</li><li>This example was identified on the 5-minute chart. No single fixed entry model was required: a 5-minute inversion FVG could be used for a precise entry, but the core lesson is recognising the accumulation-manipulation-distribution sequence itself.</li></ul>`},
  {t:'The cheat sheet',h:`<ol><li>AMD = Accumulation, Manipulation, Distribution. Also called Power of Three (PO3).</li><li>It's fractal: works on any timeframe (1-minute to 5-hour and beyond) and any asset (stocks, crypto, forex, indices).</li><li>Accumulation = range / chop. This is a no-trade zone: entering here gets you chopped up.</li><li>Manipulation = a liquidity sweep that <i>looks</i> directional but is a trap that fuels the opposite move.</li><li>Distribution = the real move. This is what you are trying to catch.</li><li>Golden rule: trade WITH the higher-time-frame trend. Look for manipulation against the trend and distribution with it.</li><li>Stack confluences: FVG + swing point, gap not closed through, key session macro time, equal highs/lows, order block respected.</li><li>There is no single mandatory entry trigger: recognising the structure comes first. A lower-time-frame inversion FVG can refine the entry once the structure is confirmed.</li><li>When price breaks a range, ask: is this distribution, or is this manipulation setting a trap? Check it against the trend before answering.</li></ol>`}
 ],
 recall:rc('Module 3','What is a liquidity sweep also commonly called?',['A stop hunt','A gap fill','A trend break','A volume spike'],'Manipulation is exactly this: a sweep of the liquidity resting at the edge of the range.'),
 see:a=>{const C=a.C,down=a.htf==='up',mir=amdScn(rr(122),{htf:'down',brk:'against'}),w=amdScn(rr(123),{htf:'up',brk:'with'});const accR=rectAt(a.acc.i0,a.acc.i1,a.acc.lo,a.acc.hi,'accumulation: no-trade zone',COL.lag,{dash:true});return[
  {focus:a.ctxEnd-4,ov:[boxOf(C,0,a.ctxEnd,COL.ice,1),tagAt(a.ctxEnd,C[a.ctxEnd].h,'higher-time-frame uptrend','above',COL.ice)],cap:'<b>Start with the higher-time-frame context.</b> Price is already in an uptrend. The setup you want continues that trend, not fights it.'},
  {focus:(a.acc.i0+a.acc.i1)/2,ov:[accR],cap:`<b>Phase 1 · Accumulation.</b> Price chops sideways between ${fm(a.acc.lo)} and ${fm(a.acc.hi)}. It looks like it is about to break out: that is exactly why it is dangerous. No directional edge yet. Do not enter.`},
  {focus:a.man[1],ov:[accR,boxOf(C,a.man[0],a.man[1],COL.bad,.8),tagAt(a.man[0],C[a.man[0]].l,'MANIPULATION: sweeps the low','below',COL.bad),hlAt(a.acc.lo,'accumulation low',COL.ice,a.acc.i0)],cap:'<b>Phase 2 · Manipulation.</b> Price makes a sharp move below the accumulation range, sweeping the stop-losses and breakout sell orders resting there. It <b>looks</b> bearish. But look at the higher-time-frame trend: it is up.'},
  {focus:a.dist0+3,ov:[accR,boxOf(C,a.dist0,C.length-1,COL.ok,1),tagAt(a.dist0,C[a.dist0].l,'DISTRIBUTION: the real move','below',COL.ok)],cap:'<b>Phase 3 · Distribution.</b> With the liquidity cleared, price moves in its true direction: up, with the higher-time-frame trend. This is the phase that pays. The manipulation was the trap, not the trade.'},
  {focus:a.man[1]+1,ov:[accR,tagAt(a.man[1],C[a.man[1]].l,'order block: last down candle','below',COL.gold),boxOf(C,a.man[1],a.man[1],COL.gold,.5)],cap:'<b>A confluence: the order block.</b> The last candle moving against the strong move before it began is the order block. If price returns to it and respects it, that adds confidence to the distribution move.'},
  {sc:{...a,C:C.slice(0,a.cut)},focus:a.man[1],ov:[accR,tagAt(a.cut-1,C[a.cut-1].l,'did it break out for real?','below',COL.gold)],cap:'<b>The instinct trap.</b> Cover the right-hand side. Price just broke the range to the downside. The natural instinct is "we broke the range, so it will keep falling". With an uptrend on the higher time frame, ask instead: is this distribution, or manipulation designed to trap sellers?'},
  {sc:w,focus:w.dist0+2,ov:[rectAt(w.acc.i0,w.acc.i1,w.acc.lo,w.acc.hi,'accumulation',COL.lag,{dash:true}),boxOf(w.C,w.dist0,w.C.length-1,COL.ok,1),tagAt(w.dist0,w.C[w.dist0].h,'break WITH the trend = distribution','above',COL.ok)],cap:'<b>When the break agrees with the trend.</b> Here the uptrend and the breakout both point up. That is distribution, the real move, not a trap. Checking against the higher-time-frame trend is the fastest way to tell the two apart.'},
  {sc:mir,focus:mir.man[1],ov:[rectAt(mir.acc.i0,mir.acc.i1,mir.acc.lo,mir.acc.hi,'accumulation',COL.lag,{dash:true}),boxOf(mir.C,mir.man[0],mir.man[1],COL.bad,.8),tagAt(mir.man[0],mir.C[mir.man[0]].h,'manipulation up','above',COL.bad),boxOf(mir.C,mir.dist0,mir.C.length-1,COL.ok,1)],cap:'<b>The mirror image.</b> In a higher-time-frame downtrend the manipulation sweeps the <b>high</b>, and distribution continues <b>down</b>. Same structure, opposite direction.'}]},
 sum:a=>({ov:[rectAt(a.acc.i0,a.acc.i1,a.acc.lo,a.acc.hi,'accumulation',COL.lag,{dash:true}),boxOf(a.C,a.man[0],a.man[1],COL.bad,.8),boxOf(a.C,a.dist0,a.C.length-1,COL.ok,1)]}),
 explain:{prompts:['Describe accumulation, manipulation and distribution, and say what you should do (or not do) in each phase.','Price breaks out of an accumulation range against the higher-time-frame trend. Explain why the natural instinct is wrong and how you should read it instead.'],
  ideas:['AMD is a structure or lens, not one specific trade trigger','It is fractal: any timeframe and any asset, because it is rooted in liquidity','Accumulation is a range: a no-trade zone where you get chopped','Manipulation is a liquidity sweep that looks directional but is a trap','Distribution is the real move that actually pays','Trade with the higher-time-frame trend: manipulate against it, distribute with it','Stack confluences: FVG with a swing point, gap not closed through, macro time, equal highs/lows, order block','When price breaks a range, ask: distribution, or the manipulation trap? Check the trend']},
 drills:[accRect,manTap,classify,obTap,sortPh,confQ],
 bank:[
  mcq('Definition','What does AMD (PO3) stand for?',['Accumulation, Manipulation, Distribution (Power of Three)','Asia, Morning, Daily','Average, Median, Deviation','Always Manage Drawdown'],'The three phases every price move cycles through.'),
  mcq('Structure','Is AMD a single mechanical trade trigger?',['No: it is a structure, a lens you look through','Yes: it is the only trigger','Only on 5m','Only on futures'],'The "operating system" behind almost every other setup.'),
  mcq('Fractal','On which timeframes does AMD show up?',['All of them: it is fractal','Only the daily','Only 5m','Only the hourly'],'The same three phases repeat at every zoom level.'),
  mcq('Fractal','On which assets does AMD apply?',['Any asset: stocks, crypto, forex, indices','Only futures','Only forex','Only Bitcoin'],'It is rooted in how liquidity behaves.'),
  mcq('Accumulation','You see price chopping in a tight range that looks like it is about to break out. What do you do?',['Don\'t enter: accumulation is a no-trade zone','Buy the bottom','Sell the top','Trade both sides'],'You will get chopped up with no directional edge yet.'),
  mcq('Manipulation','Manipulation is a move that…',['Looks directional but is designed to fuel the opposite move','Is the real trend','Is always small','Is random'],'It is the trap, not the trade.'),
  mcq('Manipulation','What does manipulation sweep?',['The liquidity at the edge of the accumulation range','The previous week\'s high','The news candle','The opening gap'],'Stop-losses and breakout orders.'),
  mcq('Distribution','Distribution is…',['The real, intended directional move that actually pays','The range phase','The trap','The news release'],'It follows the manipulation.'),
  mcq('Rule','The #1 rule is…',['Trade with the higher-time-frame trend','Trade against the trend','Trade only ranges','Trade only news'],'The single biggest edge multiplier.'),
  mcq('Rule','The higher time frame is trending up. Which AMD sequence do you want?',['Manipulation to the downside, distribution continuing up','Manipulation up, distribution down','Accumulation only','No sequence'],'Manipulate against the trend, distribute with it.'),
  mcq('Rule','Is a counter-trend scalp in the direction of the manipulation leg possible?',['Yes, technically valid, but the lower-quality option versus going with the trend','Never','Always better','It is the standard'],'Going with the trend is the better trade, every time.'),
  mcq('Instinct','Price breaks out of accumulation downside and you think "it will keep falling". During manipulation this instinct is…',['Exactly backwards: it is an early-seller trap being set','Always correct','A confirmation','Irrelevant'],'Check it against the higher-time-frame trend.'),
  mcq('Confluence','Which confluence adds extra weight simply for timing?',['A key session "macro" time such as 9:30 AM Eastern','A candle colour','A round price','The spread'],'The New York Stock Exchange open.'),
  mcq('Confluence','What is an order block?',['The last candle in the opposite direction before a strong directional move','The first candle of the day','A gap','A news bar'],'When respected, it adds confidence to the distribution move.'),
  mcq('Confluence','What does a bullish FVG with a swing low inside it represent?',['An especially strong draw on liquidity','A weak signal','A reversal','Nothing'],'Stronger than a plain FVG.'),
  mcq('Entry','Is there a single fixed entry trigger in AMD?',['No: recognise the structure first; a lower-time-frame inversion FVG is an optional refinement','Yes: always an inversion FVG','Yes: always a break of structure','Yes: always a news candle'],'Treat the IFVG as optional refinement, not a requirement.')
 ],
 exam:{bank:4,gen:[[0,1],[1,2],[2,2],[3,1],[4,1],[5,1]]},examDesc:'Marking accumulation, selecting the manipulation, telling manipulation from distribution against the trend, finding the order block, and the confluences.'});
})();
