/* ============================================================
   MODULE 0 · MARKET BASICS (first in Foundations): the plain-English words everything else uses.
============================================================ */
(()=>{
const f2=x=>Math.round(x*100)/100;
const notional=numGen('Contract value',r=>{const px=pick(r,[17500,20000,24000,27500,29000]),mn=r()<.5,pv=mn?2:20;return{q:`${mn?'MNQ':'NQ'} is trading at ${fm(px,0)}. One point is worth $${pv}. What is the total value of one contract (price × dollars per point)?`,ans:px*pv,unit:'$',tol:.5,why:`${fm(px,0)} × $${pv} = $${fm(px*pv,0)}. That is how much market you control with one contract, long before you count the small deposit that holds it (margin).`}});
const spread=numGen('The spread',r=>{const t=pick(r,[1,2,3,4]),mn=r()<.5,tv=mn?.5:5;return{q:`On ${mn?'MNQ':'NQ'} the bid is 20,000.00 and the ask is ${fm(20000+t*.25)}. The spread is ${t} tick${t>1?'s':''}. If you buy at the ask and sell straight back at the bid, how many dollars does the spread cost you on 1 contract?`,ans:t*tv,unit:'$',tol:.01,why:`${t} tick${t>1?'s':''} × $${tv} a tick = $${f2(t*tv)}. You pay the spread every time you buy and sell at the market.`}});
const move=numGen('Profit and loss',r=>{const p=pick(r,[8,12.5,15,20,32]),n=pick(r,[1,2,3,5]),mn=r()<.6,pv=mn?2:20,long=r()<.5;return{q:`You ${long?'buy':'sell'} ${n} ${mn?'MNQ':'NQ'} and the price moves ${p} points ${long?'up':'down'}, then you close. How many dollars do you make (ignore costs)?`,ans:p*n*pv,unit:'$',tol:.01,why:`${p} points × ${n} contract${n>1?'s':''} × $${pv} = $${fm(p*n*pv,0)}. You ${long?'bought':'sold'} first and the price went ${long?'up':'down'}, so it is a gain.`}});
const cost=numGen('The cost of trading',r=>{const fee=pick(r,[1.4,2,4.5]),sl=pick(r,[1,2,3]),n=pick(r,[1,2,4]),mn=fee<3,tv=mn?.5:5;return{q:`You trade ${n} ${mn?'MNQ':'NQ'}. Fees are $${fee} per contract round trip and you lose ${sl} tick${sl>1?'s':''} of slippage on entry and ${sl} on exit. What is the total cost of the trade in dollars?`,ans:f2(n*fee+2*sl*tv*n),unit:'$',tol:.02,why:`Fees ${n} × $${fee} = $${f2(n*fee)}. Slippage 2 × ${sl} tick${sl>1?'s':''} × $${tv} × ${n} = $${f2(2*sl*tv*n)}. Total $${f2(n*fee+2*sl*tv*n)}, paid win or lose.`}});
const side=r=>{const k=pick(r,[['A seller wants out right now at the best price they can get. Which price do they receive?','The bid','The ask','The last price','The settlement price','Sellers hit the bid; buyers lift the ask.'],['A buyer wants in right now. Which price do they pay?','The ask','The bid','The open','The low','Buyers pay the ask; sellers receive the bid.']]);return mcq('Bid and ask',k[0],[k[1],k[2],k[3],k[4]],k[5])};
const lev=r=>{const k=pick(r,[['A small deposit lets you control a much larger position. What is that called?','Leverage','Slippage','Spread','Volume'],['The deposit your broker or firm holds while a futures position is open is called…','Margin','The spread','Commission','A stop'],['Leverage makes a move in your favour bigger, and a move against you…','Just as much bigger','Smaller','Free','Impossible']]);return mcq('Leverage',k[0],k.slice(1,5),'Leverage multiplies both gains and losses. That is why the stop and the size come first.')};
quick({id:'m37',o:.5,ph:0,t:'Market Basics',out:'Explain what a market is, what a price is made of, and what every trade costs.',
 ls:['What a market is','Bid, ask and the spread','Volume and liquidity','Leverage and margin','What every trade costs','Trading is not investing'],
 task:'Open a chart of NQ or MNQ and find the bid and ask in the order panel. Write down the spread in ticks and dollars. Then work out the full value of one contract (price × dollars per point) and what one tick is worth.',
 learn:[
  {t:'What a market is',h:`<p>A <b>market</b> is a place where buyers and sellers meet to trade something: shares, currencies, commodities, or <b>futures contracts</b> like NQ. The place can be a physical floor or, today, a computer system called an <b>exchange</b>.</p><p>A <b>price</b> is simply the last level at which a buyer and a seller agreed. It moves when one side is more eager than the other: more eager buyers push it up, more eager sellers push it down. Everything in this course, from liquidity to gaps, is a way of reading that tug of war.</p>${def('<p><b>Trader:</b> someone who buys and sells to profit from price moves, usually over minutes to days. <b>Investor:</b> someone who holds for years. This course is about trading.</p>')}`},
  {t:'Bid, ask and the spread',h:`<p>At any moment there are two prices: the <b>bid</b> is the highest price a buyer is currently willing to pay, and the <b>ask</b> is the lowest price a seller is willing to accept. The gap between them is the <b>spread</b>.</p>${tblx(['Term','What it means','You use it when'],[['Bid','Best price buyers offer','You <b>sell</b> at the market'],['Ask','Best price sellers want','You <b>buy</b> at the market'],['Spread','Ask minus bid','It is a small cost every time you trade at the market']])}<p>On NQ the spread is usually one tick (0.25 points, $5 on NQ and $0.50 on MNQ). It gets wider when the market is thin or moving fast.</p>`},
  {t:'Volume and liquidity',h:`<p><b>Volume</b> is how many contracts changed hands. <b>Liquidity</b> (in the everyday sense) is how easily you can buy or sell without moving the price. When many people are trading, the spread is tight and your orders fill close to the price you see. When few are trading (late at night, or around holidays) the spread widens and fills are worse.</p><p>Later in this course you will meet a second meaning of "liquidity": the pools of stop orders resting above highs and below lows. Same word, related idea: orders waiting in the market.</p>`},
  {t:'Leverage and margin',h:`<p>Futures are <b>leveraged</b>: a small deposit, called <b>margin</b>, controls a much bigger position. One NQ at 29,000 is worth about <b>$580,000</b> (29,000 × $20 a point), yet you do not need that much money to trade it.</p><p>Leverage is not free money. A move in your favour is made bigger, and so is a move against you. One point on NQ is $20, so a 50-point move is $1,000 on a single contract. This is why you start on <b>MNQ</b> (one tenth the size), and why every trade in this course has a <b>stop loss</b> and a size worked out first.</p>${warn('<p>Leverage is how a small account can be wiped out by a few bad trades. Size comes from how much you can afford to lose, never from how much you hope to make.</p>')}`},
  {t:'What every trade costs',h:`<p>Winning or losing, each trade has costs:</p>${tblx(['Cost','What it is'],[['Commission and fees','What your broker and the exchange charge, per contract'],['Spread','You buy at the ask and sell at the bid'],['Slippage','Your order fills a little worse than the price you clicked, most often in fast markets']])}<p>Small per trade, but they repeat every trade. A target of a few points can be mostly eaten by costs. When you test a strategy or practise in the Eval lab, count them.</p>`},
  {t:'Trading is not investing',h:`<p>Trading is a skill and a business, not a shortcut to money. Many beginners lose money early because they trade too big, skip the stop, or try to win back a loss. This course is built around the opposite habits: a plan, a defined risk on every trade, and practice before real money.</p>${key('<p>Your first job is to <b>stay in the game</b>. Skill, patience and risk control come before profit.</p>')}<p>The next modules set up your mindset, your chart and your first order. Everything here is practice with no real money.</p>`}],
 steps:[['<b>What a price is made of.</b>',tblx(['Part','Example (NQ)'],[['Bid','20,000.00'],['Ask','20,000.25'],['Spread','1 tick = 0.25 points = $5'],['Contract value','20,000 × $20 = $400,000']])],['<b>What one trade costs.</b>',tblx(['Item','1 MNQ'],[['Fees','about $1.40'],['Slippage (1 tick each way)','$1.00'],['Total','about $2.40, before any profit or loss']])]],
 explain:{prompts:['Explain in your own words what the bid, the ask and the spread are, and when you pay the spread.','Explain what leverage is and why it makes the stop loss and your size so important.'],
  ideas:['A market is where buyers and sellers meet; price is the last agreed level','More eager buyers push price up; more eager sellers push it down','Bid = best buyer, ask = best seller, spread = the gap','You buy at the ask and sell at the bid at the market','Volume is how much traded; liquidity is how easily you can trade','Leverage lets a small deposit (margin) control a big position','Leverage magnifies gains and losses, so the stop and size come first','Every trade has fees, spread and slippage, win or lose']},
 gens:[notional,spread,move,cost,side,lev],
 bank:BANKS('Market basics',[
  ['What is a market?',['A place where buyers and sellers meet to trade','A type of news channel','A bank account','A chart indicator'],'Buyers and sellers meeting; the price is where they agree.'],
  ['What does a price represent?',['The last level where a buyer and a seller agreed','The fair value set by the exchange','The average of the day','A prediction'],'It is simply the last agreed trade.'],
  ['What is the bid?',['The highest price a buyer will currently pay','The lowest price a seller will accept','The last price','The daily high'],'Bid = buyers.'],
  ['What is the ask?',['The lowest price a seller will currently accept','The highest price a buyer will pay','The opening price','The stop price'],'Ask = sellers.'],
  ['What is the spread?',['The gap between the bid and the ask','The daily range','The size of a stop','A fee from your broker'],'It is a small cost each time you trade at the market.'],
  ['What does high volume usually mean for you?',['Tighter spreads and fills closer to the price you see','Wider spreads','The market is closed','Guaranteed profit'],'More trading means easier, cheaper fills.'],
  ['What is leverage?',['Controlling a big position with a small deposit','Making a profit without risk','A type of order','A chart tool'],'A deposit controls a much larger position.'],
  ['What does leverage do to a loss?',['Magnifies it, just like gains','Reduces it','Removes it','Nothing'],'It cuts both ways.'],
  ['What is margin?',['The deposit held while a futures position is open','A trading fee','The spread','Your profit target'],'A good-faith deposit, not a cost.'],
  ['Which is a cost of every trade, win or lose?',['Fees and slippage','Only losses','Only the stop','Nothing'],'Costs are charged either way.'],
  ['Why do beginners often start on MNQ?',['It is one tenth of the size of NQ, so risk is smaller','It always makes more','It has no fees','It cannot lose'],'Smaller dollars per point.']]),
 examDesc:'Bid, ask and spread, contract value, leverage and margin, costs and profit and loss arithmetic.'});
})();
