/* ============================================================
   MODULES 17–22 (phase 7) · ESC VLCTY (Escape Velocity)
   One indicator, two halves: New York and Asia, measured from the previous 16:00 New York close.
   Source: the ESC VLCTY complete guide and the ESC VLCTY 5.0 indicator. No performance statistics are taught here.
============================================================ */
(()=>{
const RULE={nyL:{x:.40,st:.13,rr:2,w:1},nyS:{x:.20,st:.08,rr:1.5,w:.25},asL:{x:.04,full:.10,st:.22,rr:2,half:.5},asS:{x:.10,st:.10,rr:1.5,w:.25}};
const f1=x=>Math.round(x*10)/10,f2=x=>Math.round(x*100)/100;
const pts=x=>fm(x,x%1?1:0);
const scn=r=>{const U=pick(r,[310,330,352,370,388,405]),A=pick(r,[17250,19500.25,21800.5,24100,26650.75,29252.5]);return{U,A}};
/* ---------- generators ---------- */
const avgU=numGen('What is U?',r=>{const a=Array.from({length:5},()=>pick(r,[290,310,330,350,370,390,410]));const s=a.reduce((x,y)=>x+y,0)/5;return{q:`To keep it simple, take five recent daily ranges (high minus low): ${a.join(', ')} points. What is their average? (ESC VLCTY uses 10 sessions, the arithmetic is the same.)`,ans:f1(s),unit:'pts',tol:.6,why:`(${a.join(' + ')}) ÷ 5 = ${f1(s)} points. That is U: the typical size of a day right now.`}});
const distU=numGen('Distance in U',r=>{const {U,A}=scn(r),d=pick(r,[.12,.2,.31,.4,.45,.62,-.1,-.2,-.27,-.35]);const px=A+d*U;return{q:`The 16:00 close (the anchor) was ${fm(A)} and U is ${U} points. Price is now ${fm(px)}. How far is it from the anchor, in U (two decimals, minus if below)?`,ans:f2((px-A)/U),unit:'U',tol:.015,why:`(${fm(px)} − ${fm(A)}) ÷ ${U} = ${f2((px-A)/U)} U.`}});
const frac=numGen('U in points',r=>{const U=pick(r,[300,320,350,380,400]),k=pick(r,[.4,.2,.13,.08,.22,.1]);return{q:`U is ${U} points. How many points is ${k.toFixed(2)} U?`,ans:f1(U*k),unit:'pts',tol:.6,why:`${k} × ${U} = ${f1(U*k)} points. Every distance and every stop in ESC VLCTY is a fraction of U, so the plan stretches when the market is wild and tightens when it is quiet.`}});
const nyCall=r=>{const {U,A}=scn(r),d=pick(r,[.06,.18,.25,.34,.43,.52,-.05,-.14,-.2,-.24,-.33]),px=A+d*U;const ans=d>=RULE.nyL.x?'long':d<=-RULE.nyS.x?'short':'none';
  return mcq('New York check',`It is the 09:44 candle close. The anchor is ${fm(A)}, U is ${U} points and price is ${fm(px)} (${d>=0?'+':'−'}${Math.abs(f2(d)).toFixed(2)} U). What does the New York half do?`,
  ans==='long'?['Buy at the next open','Sell at the next open','Nothing yet: check again in 15 minutes','Buy a limit lower down']:ans==='short'?['Sell at the next open','Buy at the next open','Nothing yet: check again in 15 minutes','Sell a limit higher up']:['Nothing yet: check again in 15 minutes','Buy at the next open','Sell at the next open','Skip the whole day'],
  ans==='long'?`${f2(d)} U is at least +0.40 U above the anchor: a long signal, entered at the open of the next candle.`:ans==='short'?`${f2(d)} U is at least 0.20 U below the anchor: a short signal (taken at a quarter of the size).`:`Between −0.20 U and +0.40 U nothing qualifies. The next check is 15 minutes later, and the first check that qualifies takes the trade.`)};
const nyLevels=numGen('New York stop',r=>{const U=pick(r,[320,352,370,388,405]),long=r()<.6,k=long?RULE.nyL:RULE.nyS;return{q:`A New York ${long?'long':'short'} fires and U is ${U} points. The stop is ${k.st} U. How many points is the stop?`,ans:f1(U*k.st),unit:'pts',tol:.6,why:`${k.st} × ${U} = ${f1(U*k.st)} points. The target is ${k.rr} × that, so ${f1(U*k.st*k.rr)} points.`}});
const nyTarget=numGen('New York target',r=>{const U=pick(r,[320,352,370,388,405]),long=r()<.6,k=long?RULE.nyL:RULE.nyS,st=f1(U*k.st);return{q:`A New York ${long?'long':'short'} has a ${st}-point stop. The target is ${k.rr} × the stop. How many points away is the target?`,ans:f1(st*k.rr),unit:'pts',tol:.7,why:`${st} × ${k.rr} = ${f1(st*k.rr)} points. ${long?'Longs use 2×, shorts 1.5×.':'Shorts use 1.5×, longs 2×.'}`}});
const asiaGap=r=>{const {U,A}=scn(r),g=pick(r,[.02,.03,.06,.08,.12,.15,-.04,-.08,-.12,-.19]),open=A+g*U;const take=g>=RULE.asL.x||g<=-RULE.asS.x,full=g>=RULE.asL.full;
  const ans=!take?'No trade':g>0?(full?'Long, full size':'Long, half size'):'Short, quarter size';
  const all=['Long, full size','Long, half size','Short, quarter size','No trade'];
  return mcq('Asia gap',`The 16:00 close was ${fm(A)}, U is ${U} points and Asia opened at 18:00 at ${fm(open)}. The gap is ${g>=0?'+':'−'}${Math.abs(f2(g)).toFixed(2)} U. What does the Asia half do at the 18:29 close?`,[ans,...all.filter(x=>x!==ans)],
  !take?`The gap is smaller than +0.04 U up and 0.10 U down, so the chart shows "no trade" for the night.`:g>0?`A gap of at least +0.04 U is a long. ${full?'It is +0.10 U or more, so full size.':'It is under +0.10 U, so half size.'}`:`A gap of 0.10 U or more down is a short, and shorts are a quarter of the size.`)};
const asiaStop=numGen('Asia stop',r=>{const U=pick(r,[320,352,370,388,405,687]),long=r()<.6,k=long?RULE.asL:RULE.asS;return{q:`An Asia ${long?'long':'short'} fires and U is ${U} points. The stop is ${k.st} U. How many points is the stop?`,ans:f1(U*k.st),unit:'pts',tol:.6,why:`${k.st} × ${U} = ${f1(U*k.st)} points. Asia stops are wide, so the same dollar risk buys fewer contracts.`}});
const contracts=numGen('Contracts',r=>{const risk=pick(r,[200,375,500,625,750,1000]),st=pick(r,[38,46,64,78,104]),mnq=r()<.75,pv=mnq?2:20,n=Math.max(1,Math.floor(risk/(st*pv)));return{q:`You risk $${risk} on a trade with a ${st}-point stop on ${mnq?'MNQ ($2 a point)':'NQ ($20 a point)'}. How many contracts, rounded down (minimum 1)?`,ans:n,unit:'',tol:.01,why:`$${risk} ÷ (${st} × $${pv}) = ${f2(risk/(st*pv))}, rounded down to ${Math.floor(risk/(st*pv))}${Math.floor(risk/(st*pv))<1?', so the minimum of 1':''}. ${n*st*pv>1.25*risk?`One contract already risks $${n*st*pv}, more than $${risk}: the indicator warns you.`:''}`}});
const modeRisk=numGen('Risk mode',r=>{const dd=pick(r,[1500,2000,2500,3000]),m=pick(r,[['Steady',.25],['Fast',.5],['Sprint',.7],['Funded',.1]]);return{q:`Your account's max loss is $${dd}. ${m[0]} mode risks ${m[1]*100}% of it per full-size trade. What is the full-size risk in dollars?`,ans:dd*m[1],unit:'$',tol:.01,why:`${m[1]*100}% × $${dd} = $${dd*m[1]}. Shorts and half-size Asia longs use a quarter or half of it.`}});
const dayCap=numGen('Daily loss stop',r=>{const dd=pick(r,[1500,2000,2500,3000]);return{q:`Your max loss is $${dd} and the daily loss stop is the default 60%. After losing how many dollars in a session does ESC VLCTY stop giving new trades?`,ans:dd*.6,unit:'$',tol:.01,why:`60% × $${dd} = $${dd*.6}. Asia and New York are counted separately.`}});
const timeUp=r=>{const asia=r()<.5;return mcq('The time exit',`A ${asia?'Asia':'New York'} trade has hit neither its stop nor its target. When is it closed?`,asia?['At the close of the 02:59 candle','At the 09:30 open','At 16:00','It stays open until stopped']:['At the close of the 15:54 candle','At 18:00','At 12:00','It stays open until stopped'],asia?'Asia trades are flat by 02:59.':'New York trades are flat by 15:54, before the close.')};
const first=r=>{const k=pick(r,[0,1,2]);
  const txt=['The New York checks read +0.45 U at 09:44.','The New York checks read +0.12 U at 09:44 and +0.43 U at 09:59.','Every New York check from 09:44 to 14:44 reads between −0.15 U and +0.30 U.'][k];
  const ans=['The 09:44 check takes the trade (a long)','The 09:59 check takes the trade (a long)','No New York trade today'][k];
  return mcq('First check wins',`${txt} What does the New York half do?`,[ans,...['The 09:44 check takes the trade (a long)','The 09:59 check takes the trade (a long)','No New York trade today','It waits for the strongest check of the day'].filter(x=>x!==ans)].slice(0,4),'The checks run every 15 minutes from 09:44 to 14:44. The first one that qualifies takes the trade and the New York half is then finished for the day. If none qualifies there is no trade.')};
const gen=[avgU,distU,frac];
/* ---------- m31 · the idea ---------- */
quick({id:'m31',o:17.1,ph:6,t:'ESC VLCTY: The Idea',out:'Explain what the anchor and U are, and why price far from the anchor tends to keep going.',
 ls:['What ESC VLCTY is','The anchor: the previous 16:00 close','U: the size of a normal day','Everything is a fraction of U','Two halves, one indicator','Longs lead, shorts stay small'],
 task:'Open an NQ 1-minute chart. Mark the 16:00 close from yesterday. Find the last ten daily ranges (high minus low) and average them to get U. Then write down 0.40 U and 0.20 U in points: those are today\'s New York trigger distances.',
 learn:[
  {t:'What ESC VLCTY is',h:`<p><b>ESC VLCTY</b> is short for <b>Escape Velocity</b>. It is a second trading model, separate from ECHO X ORBIT, and it is built on one simple idea: once price has pulled <b>far enough away from a fixed reference price</b>, it tends to keep going. It has "escaped".</p><p>It is <b>one indicator with two halves</b>: one for the New York session and one for the Asia session into the overnight. Both do the same job, measure how far price has moved from the reference and ride that move, with fixed rules, so there is no discretion about whether a signal is there.</p>`},
  {t:'The anchor',h:`<p>The reference price is the <b>previous 16:00 New York close</b>: the close of the regular trading session. ESC VLCTY calls it the <b>anchor</b>. It is a price every trader in the world agrees on, because it is where the cash session ended.</p>${key('<p>Every distance in ESC VLCTY is measured from the <b>anchor</b>. Gap in Asia = the 18:00 open minus the anchor. Distance in New York = current price minus the anchor.</p>')}`},
  {t:'U: the size of a normal day',h:`<p>A 100-point move means something very different in a quiet week and a wild one. ESC VLCTY solves this with <b>U</b>: the <b>average high-to-low range of the last 10 daily sessions</b>. Today, 1 U is roughly 350 to 400 NQ points, but it changes with the market.</p><p>Because U is recalculated every day, the model measures every move against the <b>current</b> size of a day, not against a fixed number of points.</p>`},
  {t:'Everything is a fraction of U',h:`<p>Triggers, stops and gaps are all written as fractions of U, which is why the plan "automatically gets wider when the market is wild and tighter when it is quiet".</p>${tblx(['What','New York','Asia'],[['Long trigger','price +0.40 U above the anchor','gap +0.04 U or more'],['Short trigger','price 0.20 U below the anchor','gap 0.10 U or more below'],['Long stop','0.13 U','0.22 U'],['Short stop','0.08 U','0.10 U']])}<p>You will learn each of these in the next modules. For now just notice: no fixed points, only fractions of U.</p>`},
  {t:'Two halves, one indicator',h:`<p>The <b>Asia half</b> makes one decision a night, at the close of the 18:29 candle, by looking at the gap. The <b>New York half</b> checks every 15 minutes through the morning and takes the <b>first</b> check that qualifies. There is at most <b>one Asia trade and one New York trade a day</b>.</p><p>You use the <b>1-minute chart</b>. The indicator warns you if you are on any other time frame.</p>`},
  {t:'Longs lead, shorts stay small',h:`<p>The plan trades both directions, but it does not treat them equally. The <b>long side carries the edge</b>. The short side is much closer to a coin flip, so shorts are traded at a <b>quarter of the full size</b> (and some Asia longs at half). This is a sizing choice, not a prediction: you lean on the side that works and keep the other small.</p>${warn('<p>Nothing in ESC VLCTY is a promise. The edge is modest and the rules were chosen after testing many settings, so live results can be weaker than any test. That is why you start small and journal your own fills (Module on routine).</p>','Be honest about it')}`}],
 recall:rc('Orders & Your First Trade','What does a stop order do?',['Closes your trade at a set price to limit the loss','Opens a trade at a better price','Doubles your size','Cancels the target'],'ESC VLCTY puts the stop in at the same time as the entry, every time.'),
 steps:[['<b>The anchor and U.</b>',tblx(['Item','What it is'],[['Anchor','The previous 16:00 New York close'],['U','The average daily high-to-low range of the last 10 sessions'],['Distance','(price − anchor) ÷ U']])],['<b>One example.</b>',tblx(['Step','Number'],[['Anchor','29,252.50'],['U','352 points'],['Price','29,403.50'],['Distance','(29,403.50 − 29,252.50) ÷ 352 = +0.43 U']])]],
 explain:{prompts:['Explain in your own words what the anchor and U are, and why every ESC VLCTY distance is a fraction of U.','Describe the two halves of ESC VLCTY and why shorts are traded smaller than longs.'],
  ideas:['The anchor is the previous 16:00 New York close','U is the average high-to-low range of the last 10 sessions','Distances are fractions of U, so they scale with volatility','Once price is far enough from the anchor it tends to keep going: escape velocity','Asia half decides once a night at 18:29; New York checks every 15 minutes','At most one Asia trade and one New York trade a day','Longs carry the edge; shorts are a quarter of the size','You use the 1-minute chart']},
 gens:gen,
 bank:BANKS('ESC VLCTY',[
  ['What is the anchor?',['The previous 16:00 New York close','The 09:30 open','The weekly open','The 18:00 open'],'Every distance is measured from the previous 16:00 close.'],
  ['What is U?',['The average high-to-low range of the last 10 daily sessions','The average closing price','Yesterday\'s range only','The 4H ATR'],'U is the typical size of a day right now.'],
  ['Why are stops and triggers fractions of U?',['So the plan widens when the market is wild and tightens when it is quiet','To make the numbers look small','Because NQ has no fixed tick','Because it is required by prop firms'],'U scales every distance with volatility.'],
  ['Which time frame does ESC VLCTY use?',['The 1-minute chart','The daily chart','The 4-hour chart','Any time frame'],'The indicator prints a warning on any other time frame.'],
  ['How many trades per session can ESC VLCTY take?',['One per half: one Asia and one New York a day','As many as qualify','Three','None on Fridays'],'One Asia trade and one New York trade a day, at most.'],
  ['Why are shorts traded at a quarter of the size?',['The long side carries the edge; shorts are much closer to a coin flip','Shorts are illegal on NQ','Shorts have wider stops','The indicator cannot short'],'It is a sizing decision: lean on the side that works.'],
  ['"Escape velocity" refers to…',['Price moving far enough from the anchor that it tends to keep going','The speed of a candle','A news spike','The 1-minute time frame'],'Once price has pulled far enough away, it has escaped.'],
  ['Does ESC VLCTY ask you to judge each setup by feel?',['No: the rules are fixed and measurable','Yes, every signal','Only in Asia','Only on news days'],'Fixed rules mean no discretion about whether a signal is there.']]),
 examDesc:'The anchor, U, distances as fractions of U, and the two halves.'});
/* ---------- m32 · New York ---------- */
quick({id:'m32',o:17.2,ph:6,t:'ESC VLCTY: The New York Half',out:'Say exactly when a New York trade fires, and place its stop and target.',
 ls:['The 21 checks','The long rule','The short rule','Entry: the next open, at market','Stop, target and the time exit','One trade, then done'],
 task:'On tomorrow\'s New York morning, mark the anchor, the +0.40 U line and the −0.20 U line at 09:30. At the close of 09:44, 09:59, 10:14 … write the distance in U. Note which check (if any) would have fired and where the stop and target would sit.',
 learn:[
  {t:'The 21 checks',h:`<p>The New York half does not wait for a pattern. At the close of the <b>09:44, 09:59, 10:14 ... 14:44 candles</b> (every 15 minutes, 21 checks) it asks one question: <b>is price far enough from the anchor?</b></p>${key('<p>The <b>first</b> check where the answer is yes takes the trade. After that the New York half is finished for the day. If no check qualifies by 14:44, there is no New York trade.</p>')}`},
  {t:'The long rule',h:`<p>If price is at least <b>+0.40 U above the anchor</b> at a check, ESC VLCTY buys. Stop <b>0.13 U</b> away, target <b>2 × the stop</b>, and <b>full size</b>.</p>${tblx(['Example','Value'],[['Anchor','29,252.50'],['U','352 points'],['Price at 09:44','29,403.50 (+0.43 U)'],['Stop','0.13 × 352 = 45.8 points'],['Target','2 × 45.8 = 91.6 points']])}`},
  {t:'The short rule',h:`<p>If price is at least <b>0.20 U below the anchor</b>, ESC VLCTY sells. Stop <b>0.08 U</b>, target <b>1.5 × the stop</b>, and only a <b>quarter</b> of full size. The trigger is closer (0.20 U against 0.40 U) because shorts are small and quick.</p>`},
  {t:'Entry: at market, on the next open',h:`<p>The signal candle has to <b>close</b> before the check is known. The entry is at the <b>open of the next candle</b>, a <b>market order</b>, never a limit. Chasing is not allowed either: if you are more than a few points past the planned entry, skip it.</p><p>Pulling back to a better price sounds smart, but the strongest moves are exactly the ones that never pull back, so a limit entry misses them. That is why the entry stays at the market.</p>`},
  {t:'Stop, target and the time exit',h:`<p>Put the stop in <b>at the same time</b> as the entry. The trade ends at the stop, at the target, or flat at the close of the <b>15:54</b> candle, whichever comes first. If a candle touches both the stop and the target, treat it as a stop.</p>${warn('<p>Do not move the stop wider, remove it, or change the target because "it looks like it will reverse". The rules only work if you follow them every time.</p>')}`},
  {t:'One trade, then done',h:`<p>Once the New York half has taken its trade it takes no more that day. After you lose, the plan does nothing different: no revenge trade, no doubling, no skipping the next signal. There is also a <b>daily loss stop</b>: once you have lost a set share of your max loss in the session, no new trade (Module on sizing).</p>`}],
 recall:rc('Time Theory & Session Timing','Which session runs from 9:30 AM to 4:00 PM New York time?',['The New York regular session','London','Asia','Pre-market'],'ESC VLCTY measures from the end of this session (the 16:00 close) and trades the next one.'),
 steps:[['<b>The check.</b>',tblx(['Time','Price','Distance','Fires?'],[['09:44','29,284','+0.09 U','no'],['09:59','29,392','+0.40 U','long'],['10:14','not checked','','done for the day']])],['<b>The levels.</b>',tblx(['Line','Value'],[['Entry','next candle open + 1 tick'],['Stop','entry − 0.13 U'],['Target','entry + 2 × stop'],['Exit','stop, target or 15:54']])]],
 explain:{prompts:['Walk through a New York long from the 09:44 check to the exit.','Explain why the entry is a market order on the next open and not a limit order.'],
  ideas:['21 checks every 15 minutes from the 09:44 close to the 14:44 close','The first check that qualifies takes the trade','Long: +0.40 U above the anchor, stop 0.13 U, target 2x, full size','Short: 0.20 U below the anchor, stop 0.08 U, target 1.5x, quarter size','Entry at market on the open of the candle after the signal','Stop goes in with the entry; never move it','Flat at the 15:54 candle close if neither is hit','One New York trade a day; no revenge or doubling']},
 gens:[distU,nyCall,nyLevels,nyTarget],
 bank:BANKS('New York',[
  ['When does the New York half look for a trade?',['At the close of the 09:44, 09:59 … 14:44 candles','Only at 09:30','Only at 16:00','Whenever a pattern forms'],'21 checks, every 15 minutes.'],
  ['How far above the anchor must price be for a long?',['At least +0.40 U','+0.04 U','+1 U','Any distance'],'The New York long trigger is +0.40 U.'],
  ['How far below the anchor must price be for a short?',['At least 0.20 U','0.40 U','0.04 U','Any distance'],'The New York short trigger is −0.20 U.'],
  ['What is the New York long stop?',['0.13 U','0.22 U','0.08 U','A fixed 20 points'],'Stops are fractions of U.'],
  ['What is the New York short target?',['1.5 × the stop','2 × the stop','1 × the stop','3 × the stop'],'Shorts use 1.5×; longs 2×.'],
  ['How do you enter?',['At market on the next candle\'s open','With a limit order at a pullback','At the signal candle\'s high','On the 5-minute chart'],'A market order on the next open, never a limit.'],
  ['What happens when a candle touches both the stop and the target?',['Treat it as a stop','Treat it as a target','Close at break-even','Add a contract'],'The conservative assumption is a loss.'],
  ['When is an open New York trade closed at the latest?',['At the close of the 15:54 candle','At 12:00','At 18:00','Never'],'Flat before the close.'],
  ['What do you do after a loss?',['Nothing different: no revenge, no doubling, no skipping','Double the next trade','Skip the next signal','Widen the stop'],'The plan has no reaction to a loss.']]),
 examDesc:'The 21 checks, the long and short rules, the levels and the exits.'});
/* ---------- m33 · Asia ---------- */
quick({id:'m33',o:17.3,ph:6,t:'ESC VLCTY: The Asia Half',out:'Read the Asia gap and say whether it is a long, a short or no trade.',
 ls:['The gap','The decision at 18:29','Asia longs: full size and half size','Asia shorts','Why the stops are wide','How an Asia trade ends'],
 task:'For the next five evenings, write down the 16:00 close, the 18:00 open and the gap in U. Decide long, short or no trade at 18:29 and note where the stop and target would be. Check what happened by 02:59.',
 learn:[
  {t:'The gap',h:`<p>At 18:00 New York time the futures session reopens. The <b>gap</b> is the 18:00 open minus the anchor (the 16:00 close), measured in U. A positive gap means the market reopened above the anchor; a negative gap means below.</p>`},
  {t:'The decision at 18:29',h:`<p>The Asia half makes <b>one decision a night</b>, at the close of the <b>18:29</b> candle, and trades at the <b>18:30 open</b>. Every night the chart draws a box and a label "ASIA gap +X U". A tick (✓) means a trade, a cross (✗ no trade) means the gap was too small.</p>`},
  {t:'Asia longs: full size and half size',h:`<p>A gap of at least <b>+0.04 U</b> is a long. Stop <b>0.22 U</b>, target <b>2 × the stop</b>. If the gap is <b>+0.10 U or more</b> the trade is full size; a smaller gap is <b>half size</b>. A bigger gap is stronger evidence, so it gets more risk.</p>`},
  {t:'Asia shorts',h:`<p>A gap of at least <b>0.10 U below</b> the anchor is a short. Stop <b>0.10 U</b>, target <b>1.5 × the stop</b>, a <b>quarter</b> of full size. Same principle as New York: the side with less edge gets less risk.</p>`},
  {t:'Why the stops are wide',h:`<p>Asia stops are much wider than New York stops (often 80 to 100 points on a long). Overnight trading is thin, so the price swings around more before it settles. The dollar risk is the same <b>1 R</b>, just in fewer contracts. If your platform cannot hold overnight, use a smaller size or skip Asia.</p>${warn('<p>Asia has thin liquidity at 18:00 to 18:30. Real fills can be worse than at the New York open. Journal your fills.</p>')}`},
  {t:'How an Asia trade ends',h:`<p>The trade ends at the stop, at the target, or flat at the close of the <b>02:59</b> candle. Most Asia longs end at the time exit: they run for hours and are closed by the clock. You can sleep, because the stop is a real order at your broker.</p>`}],
 recall:rc('Time Theory & Session Timing','Which session opens at 6:00 PM New York time?',['Asia','London','New York','Pre-market'],'The ESC VLCTY Asia half starts from the 18:00 open.'),
 steps:[['<b>The gap.</b>',tblx(['Item','Value'],[['Anchor (16:00 close)','25,465.00'],['U','366 points'],['18:00 open','25,604.00'],['Gap','+0.38 U']])],['<b>The decision.</b>',tblx(['Gap','Action'],[['+0.10 U or more','Long, full size'],['+0.04 to +0.10 U','Long, half size'],['between','No trade'],['−0.10 U or more','Short, quarter size']])]],
 explain:{prompts:['Explain how the Asia half decides between long, short and no trade, and what size each gets.','Why are Asia stops wide, and what does that mean for how many contracts you trade?'],
  ideas:['Gap = 18:00 open minus the anchor, in U','One decision a night at the close of the 18:29 candle; entry at the 18:30 open','Long: gap +0.04 U or more, stop 0.22 U, target 2x','Full size if the gap is +0.10 U or more, otherwise half','Short: gap 0.10 U or more down, stop 0.10 U, target 1.5x, quarter size','Asia stops are wide so the same dollar risk is fewer contracts','Ends at the stop, the target or flat at the 02:59 candle close','No-trade nights are normal']},
 gens:[asiaGap,asiaStop,timeUp],
 bank:BANKS('Asia',[
  ['When does the Asia half decide?',['At the close of the 18:29 candle, once a night','Every 15 minutes','At 16:00','At midnight'],'One decision a night, entered at the 18:30 open.'],
  ['How is the Asia gap measured?',['The 18:00 open minus the 16:00 close, in U','The 16:00 open minus the 18:00 close','High minus low','The weekly gap'],'Gap in U relative to the anchor.'],
  ['What gap triggers an Asia long?',['At least +0.04 U','+0.10 U only','+0.40 U','Any gap'],'+0.04 U or more.'],
  ['When is an Asia long full size?',['When the gap is +0.10 U or more','Always','Never','When it is below +0.04 U'],'Bigger gap, bigger size; smaller gaps use half.'],
  ['What gap triggers an Asia short?',['At least 0.10 U below the anchor','0.04 U below','Any gap down','+0.10 U'],'The short side needs a bigger gap and trades at a quarter of the size.'],
  ['What is the Asia long stop?',['0.22 U','0.13 U','0.10 U','A fixed 40 points'],'The Asia long stop is 0.22 U.'],
  ['Why do Asia stops look so wide?',['Overnight trading is thin and swings more','Because the target is bigger','Because shorts are bigger','They are a mistake'],'Thin markets, wider stops, fewer contracts.'],
  ['What does a "✗ no trade" label mean?',['The gap was too small, so there is no trade tonight','The indicator broke','You must trade anyway','The stop is too wide'],'No trade is a normal result.'],
  ['When does an open Asia trade end at the latest?',['At the close of the 02:59 candle','At 09:30','At 16:00','At midnight'],'Flat by 02:59.']]),
 examDesc:'The Asia gap, the decision at 18:29, long, short and half-size rules, and the exit.'});
/* ---------- m34 · sizing ---------- */
quick({id:'m34',o:17.4,ph:6,t:'ESC VLCTY: Sizing & Risk Modes',out:'Turn a risk mode and a stop into a number of contracts.',
 ls:['Contracts come from risk, not feel','MNQ and NQ','Steady, Fast, Sprint, Funded','The daily loss stop','Evaluations: pick a mode and keep it','Funded accounts: stay alive'],
 task:'Write down your account\'s max loss limit. Pick the mode you would use for an evaluation. Work out the full-size dollar risk, then the contracts for a 64-point New York long stop on MNQ and on NQ.',
 learn:[
  {t:'Contracts come from risk, not feel',h:`<p>The indicator sizes every trade for you: <b>contracts = dollar risk ÷ (stop in points × dollars per point)</b>, rounded down, minimum 1. Shorts and half-size Asia longs take a quarter or half of that.</p>${tblx(['Example','Number'],[['Risk','$500'],['Stop','64 points'],['MNQ ($2 a point)','500 ÷ (64 × 2) = 3.9, so 3 contracts'],['NQ ($20 a point)','500 ÷ (64 × 20) = 0.4, so 1 contract (a warning)']])}`},
  {t:'MNQ and NQ',h:`<p>MNQ is $2 a point, NQ is $20 a point. One NQ at a 64-point stop is $1,280 of risk. On a small account that is far more than you chose, and the label shows <b>"⚠ above your $X"</b>. Use <b>MNQ</b> on accounts under about 150K, or choose a bigger mode knowingly.</p>`},
  {t:'Steady, Fast, Sprint, Funded',h:`<p>The mode is the share of your <b>max loss limit</b> you risk on one full-size trade:</p>${tblx(['Mode','Full-size risk','Use it for'],[['Steady','25% of max loss','The best chance to pass: the most room'],['Fast','50%','A quicker finish, more risk of failing'],['Sprint','70%','Fastest, likely to fail: only with a cheap fee'],['Funded','10%','Small and careful, to keep the account']])}<p>Standard max losses by size: 25K = $1,500, 50K = $2,000, 75K = $2,500, 100K = $3,000, 150K = $4,500. If your firm differs, enter your own number.</p>`},
  {t:'The daily loss stop',h:`<p>After you lose a set share of your max loss in a session (default <b>60%</b>), ESC VLCTY gives no new trade in that session. On a $2,000 limit that is $1,200. Asia and New York are counted separately. Keep it on.</p>`},
  {t:'Evaluations: pick a mode and keep it',h:`<p>Choose the mode <b>before the first trade</b> of an attempt and do not change it mid-attempt. Do not add size because you are close to the target. Firms with consistency rules want a steady pace, so Steady fits there. Firm rules change: check your firm's current rules and set your max loss limit to your account's number.</p>`},
  {t:'Funded accounts: stay alive',h:`<p>On a funded account the goal is payouts, not speed. Use <b>Funded</b> mode (10%) or Steady and keep the daily loss stop on. A blown funded account costs you the account. Before each session check your remaining drawdown, set the mode and make sure both alerts are active.</p>`}],
 recall:rc('Risk Management','What does the max loss limit of a prop account control?',['How far the account can fall before it is closed','How many trades you take','Your profit target','Your payout split'],'ESC VLCTY sizes everything as a share of this number.'),
 steps:[['<b>From mode to contracts.</b>',tblx(['Step','Number'],[['Max loss','$2,000'],['Steady (25%)','$500 full-size risk'],['NY long stop','64 points'],['MNQ','500 ÷ 128 = 3 contracts']])],['<b>Smaller sizes.</b>',tblx(['Trade','Share of full risk'],[['NY long','100%'],['NY short','25%'],['Asia long, gap ≥ +0.10 U','100%'],['Asia long, small gap','50%'],['Asia short','25%']])]],
 explain:{prompts:['Explain how ESC VLCTY turns a risk mode and a stop into a number of contracts.','Why use MNQ on a small account, and what does the "above your $X" warning mean?'],
  ideas:['Contracts = dollar risk ÷ (stop × dollars per point), rounded down, minimum 1','MNQ is $2 a point, NQ $20 a point','Steady 25%, Fast 50%, Sprint 70%, Funded 10% of the max loss','Shorts and half-size Asia longs risk a quarter or a half','The daily loss stop (60% by default) blocks new trades in that session','Pick the mode before the evaluation and keep it','Funded: small and careful, stay alive for payouts','A warning means even one contract risks more than you chose']},
 gens:[contracts,modeRisk,dayCap],
 bank:BANKS('Sizing',[
  ['How are contracts calculated?',['Dollar risk ÷ (stop in points × dollars per point), rounded down','Account size ÷ 1,000','Always 1 contract','By feel'],'The indicator sizes by risk, never by feel.'],
  ['How much is one point on MNQ?',['$2','$20','$0.50','$5'],'MNQ is $2 a point.'],
  ['How much is one point on NQ?',['$20','$2','$5','$0.25'],'NQ is $20 a point.'],
  ['What does Steady mode risk on a full-size trade?',['25% of the max loss limit','50%','10%','70%'],'Steady is the most conservative evaluation mode.'],
  ['Which mode is meant for funded accounts?',['Funded: 10% of the max loss','Sprint','Fast','No mode'],'Small and careful: payouts, not speed.'],
  ['What does "⚠ above your $X" mean?',['One contract already risks more than your chosen amount','The trade will win','The stop is missing','The alert failed'],'Use MNQ, a bigger mode knowingly, or skip.'],
  ['What does the daily loss stop do?',['Blocks new trades in that session after the set loss','Closes your open trade','Doubles your size','Moves the stop'],'60% of your max loss by default, per session.'],
  ['When should you pick the risk mode for an evaluation?',['Before the first trade, then keep it','After every loss','When you are close to the target','Each morning'],'Do not change it mid-attempt.'],
  ['What is the right way to size a short?',['At a quarter of the full risk','At double','At full size','Without a stop'],'Shorts carry the least edge.']]),
 examDesc:'Contracts from risk and stop, MNQ against NQ, the four risk modes and the daily loss stop.'});
/* ---------- m35 · setup, fills, routine ---------- */
quick({id:'m35',o:17.5,ph:6,t:'ESC VLCTY: Setup, Fills & Your Routine',out:'Set up the indicator, read what it draws, and run the daily routine.',
 ls:['Setting it up in TradingView','Reading the chart','Alerts','Your day, hour by hour','Fills in the real world','Do and don\'t, honest limits'],
 task:'Add ESC VLCTY to a 1-minute NQ or MNQ chart. Set your contract, account size and mode. Create the alert. Then write the day\'s times on a card: 18:29, 09:44 to 14:44, 15:54, 02:59.',
 learn:[
  {t:'Setting it up in TradingView',h:`<ol><li>Open NQ or MNQ on the <b>1-minute</b> chart, on the continuous front-month contract.</li><li>Add the ESC VLCTY indicator. One indicator runs both sessions. Remove any older indicator it replaces.</li><li>Open the settings. Group 1: your contract and account size. Group 2: the risk mode and the daily loss stop. Group 3: options (sessions, lines, labels). Group 4 holds the tested numbers: best left alone. Group 5 is colors.</li></ol><p>The indicator needs about ten days of history to compute U.</p>`},
  {t:'Reading the chart',h:`<ul><li>A grey <b>box</b> from 09:30 to the signal candle labelled "NY +0.45 U ✓" shows how far price travelled from the anchor.</li><li>A <b>blue dashed</b> line is the entry, <b>red dotted</b> the stop, <b>green dotted</b> the target.</li><li>The <b>label</b> shows direction, size, entry, stop, target, R:R, contracts and dollars at risk, a live P&amp;L and then the final result.</li><li>VWAP and its bands are drawn for reference only: they do not change any trade.</li></ul>`},
  {t:'Alerts',h:`<p>Click the alert clock, choose the indicator and the condition <b>"Any alert() function call"</b>, once per bar close. You get a message when a trade starts (direction, stop, target, contracts) and when it ends. One alert covers both sessions. The indicator does not place orders: you place them yourself or with your own tools.</p>`},
  {t:'Your day, hour by hour',h:tblx(['Time (ET)','What happens','What you do'],[['16:00','The close becomes tomorrow\'s anchor','Nothing'],['18:00','Asia opens; the gap is measured','Nothing'],['18:29','Asia decision: ✓ trade or ✗ none','If it fires, place the order'],['02:59','Any open Asia trade is flat','Nothing'],['09:30','Anchor and trigger lines drawn','Know where the triggers are'],['09:44 to 14:44','A check every 15 minutes','When it fires, market order on the next candle'],['15:54','Any New York trade flat','Close manually if needed']])},
  {t:'Fills in the real world',h:`<p>Tests are always cleaner than real life. Your entry is a market order after the signal candle closes, so a fast market can fill several points from the candle open. Spreads are wide at 18:00 to 18:30, and a stop in a news spike can slip. Every extra point of slippage costs you, so <b>journal your real fills</b> (signal time, fill price, result) and compare after 50 to 100 trades.</p>`},
  {t:'Do and don\'t, honest limits',h:tblx(['Do','Don\'t'],[['Use the 1-minute chart and the continuous contract','Change stops or targets because it "looks like it will reverse"'],['Enter at market on the candle after the signal','Chase a trade more than a few points past the planned entry'],['Put the stop in with the entry','Widen the stop or remove it'],['Take every signal in the same mode for at least 100 trades','Skip trades you "don\'t like"'],['Keep the daily loss stop','Add a second trade after a loss to "make it back"'],['Use MNQ until your account is big enough for NQ','Size by feel']])+key('<p>ESC VLCTY is a modest edge, not a secret setting. The side with the edge is the long side. Forward-test small (MNQ, Steady) before you trust it with more, and remember nothing here is financial advice: you can lose your whole account or evaluation fee.</p>','Honest limits')}],
 recall:rc('Trading Psychology & Discipline','What is the best response to a losing trade?',['Follow the plan on the next signal','Double the size','Skip the next signal','Remove the stop'],'ESC VLCTY has no reaction to a loss: the plan stays the same.'),
 steps:[['<b>A day on the clock.</b>',tblx(['Time','Action'],[['18:29','Asia check'],['02:59','Asia flat'],['09:44 – 14:44','New York checks'],['15:54','New York flat']])],['<b>What goes in the journal.</b>',tblx(['Field','Why'],[['Signal time','Check the rule fired'],['Fill price','Measure slippage'],['Result in R','Compare with the plan'],['Followed the rules?','The only thing you control']])]],
 explain:{prompts:['Describe how to set up ESC VLCTY and what each part of the chart means.','Explain why you journal your fills and why you forward-test small.'],
  ideas:['1-minute chart on the continuous contract; one indicator runs both sessions','Settings: contract, account size, risk mode, daily loss stop','Box = distance from the anchor; blue entry, red stop, green target','Alert: any alert() function call, once per bar close','The indicator does not place orders','Fills in real life are worse than a clean test, so journal them','Take every signal in the same mode: no skipping, no revenge','Forward-test small before trusting it']},
 gens:[timeUp,first,contracts],
 bank:BANKS('Routine',[
  ['Which chart do you use?',['The 1-minute chart on the continuous contract','The 15-minute chart','The daily chart','Any chart'],'The indicator warns you on any other time frame.'],
  ['Does the indicator place orders?',['No: you place them or use your own tools','Yes, automatically','Only in Asia','Only on MNQ'],'It draws and alerts; you execute.'],
  ['Which alert condition do you pick?',['"Any alert() function call", once per bar close','Crossing','Greater than','Once only'],'One alert covers both sessions.'],
  ['What does the grey box on the chart show?',['How far price travelled from the anchor','The stop distance','The target','The spread'],'It is the measuring box.'],
  ['What colour is the stop line?',['Red dotted','Blue dashed','Green dotted','White'],'Blue dashed entry, red dotted stop, green dotted target.'],
  ['Why compare your real fills to the plan?',['Real fills are worse than clean tests, and you need to know by how much','To change the rules','To skip trades','To increase size'],'Journal signal time, fill and result.'],
  ['What do you do after a loss?',['Take the next signal exactly as planned','Skip the next one','Double','Widen the stop'],'No revenge, no doubling, no skipping.'],
  ['Which side carries the edge?',['The long side','The short side','Neither','Only Asia shorts'],'Shorts are traded at a quarter of the size.'],
  ['Before trusting it with more size you should…',['Forward-test small (MNQ, Steady) first','Use NQ immediately','Skip the journal','Change the settings'],'Small and careful first.']]),
 examDesc:'Setup, reading the chart, alerts, the daily clock, real-world fills and the do and don\'t list.'});
/* ---------- m36 · worked trades ---------- */
const WT=[
 ['New York long','09:44 ET. Price is +0.43 U from the 16:00 close of 29,252.50 (U = 352 points).','Entry 29,404.50, stop 29,358.68 (45.8 points), target 29,496.14 (91.6 points).','target','+1.99 R','A clean win: the move kept going and the 2× target filled.'],
 ['New York long','09:44 ET. Price is +0.84 U from the 16:00 close of 29,434.00 (U = 351 points).','Entry 29,730.25, stop 29,684.65 (45.6 points), target 29,821.44 (91.2 points).','stop','−1.02 R','The market was far above the anchor, but it pulled back right after the entry. This is the normal losing trade: 1 R lost.'],
 ['New York short','09:44 ET. Price is −0.20 U from the 16:00 close of 29,818.00 (U = 388 points).','Entry 29,738.75, stop 29,769.78 (31.0 points), target 29,692.20 (46.5 points).','target','+1.48 R','Shorts are a quarter of the size, so even a clean win is small money.'],
 ['Asia long','18:29 ET. The gap is +0.38 U from the 16:00 close of 25,465.00 (U = 366 points).','Entry 25,753.25, stop 25,672.78 (80.5 points), target 25,914.18 (160.9 points).','target','+1.99 R','A big gap, so full size, and a target hit within hours.'],
 ['Asia long','18:29 ET. The gap is +0.11 U from the 16:00 close of 29,792.50 (U = 405 points).','Entry 29,771.00, stop 29,681.92 (89.1 points), target 29,949.16 (178.2 points).','stop','−1.01 R','Price fell back below the gap open before the entry candle and kept falling. Asia stops are wide, so the dollar loss is the same 1 R in fewer contracts.'],
 ['Asia short','18:29 ET. The gap is −0.19 U from the 16:00 close of 27,631.00 (U = 687 points).','Entry 27,731.50, stop 27,800.16 (68.7 points), target 27,628.51 (103.0 points).','stop','−1.01 R','A quarter-size short that was stopped: small loss, as designed.']];
const wt=r=>{const w=pick(r,WT);return mcq('Read the trade',`${w[0]}. ${w[1]} ${w[2]} How did it end?`,[`${w[3]==='target'?'Target':'Stop'} · ${w[4]}`,`${w[3]==='target'?'Stop · −1.0 R':'Target · +2.0 R'}`,'Flat at the time exit · about 0 R','Skipped: it never fired'],w[5])};
const wtSize=numGen('Size the trade',r=>{const w=pick(r,WT),st=parseFloat(w[2].match(/\(([\d.]+) points\)/)[1]),risk=pick(r,[500,375,200]);const n=Math.max(1,Math.floor(risk/(st*2)));return{q:`${w[0]}: the stop is ${st} points. You trade MNQ ($2 a point) and your full-size risk is $${risk}. How many contracts at full size, rounded down (minimum 1)?`,ans:n,unit:'',tol:.01,why:`$${risk} ÷ (${st} × $2) = ${f2(risk/(st*2))}, so ${n} contract${n>1?'s':''}.`}});
quick({id:'m36',o:17.6,ph:6,t:'ESC VLCTY: Worked Trades & Make the Call',out:'Read real ESC VLCTY trades from anchor to result, and make the call on new ones.',
 ls:['A New York long that won','A New York long that lost','A short, kept small','An Asia long that won','An Asia long that lost','What every trade has in common','Get the indicator and ask your questions'],
 task:'Take each of the six worked trades below and rebuild it: anchor, U, distance, entry, stop, target. Then find your own last three signals in the replay and do the same.',
 learn:[
  {t:'A New York long that won',h:`<p>${WT[0][1]}</p><p>${WT[0][2]}</p><p><b>Result:</b> ${WT[0][4]}. ${WT[0][5]}</p>`},
  {t:'A New York long that lost',h:`<p>${WT[1][1]}</p><p>${WT[1][2]}</p><p><b>Result:</b> ${WT[1][4]}. ${WT[1][5]}</p>${key('<p>A loss like this is not a mistake. The signal was valid and the trade followed the plan: the cost was one R, a number you chose before you entered.</p>')}`},
  {t:'A short, kept small',h:`<p>${WT[2][1]}</p><p>${WT[2][2]}</p><p><b>Result:</b> ${WT[2][4]}. ${WT[2][5]}</p>`},
  {t:'An Asia long that won',h:`<p>${WT[3][1]}</p><p>${WT[3][2]}</p><p><b>Result:</b> ${WT[3][4]}. ${WT[3][5]}</p>`},
  {t:'An Asia long that lost',h:`<p>${WT[4][1]}</p><p>${WT[4][2]}</p><p><b>Result:</b> ${WT[4][4]}. ${WT[4][5]}</p>`},
  {t:'What every trade has in common',h:`<p>Different sessions, different results, the same process: measure from the <b>anchor</b>, scale by <b>U</b>, enter at <b>market on the next open</b>, stop in at once, target at a fixed multiple, flat by the clock. The only thing that varies is whether price keeps going. Your job is to run the process the same way every time and keep every loss at 1 R.</p>`},
  {t:'Get the indicator and ask your questions',h:`<p>That is the whole model. To get the <b>ESC VLCTY indicator</b> on your own TradingView chart, <b>send Hannah a DM on Discord</b> to set up a <b>Zoom call</b>. On the call she shares the indicator to your TradingView account and sets it up with you.</p><p>The call is also where you can <b>ask any questions you want</b>, about ESC VLCTY, the other models in this school or your own trading.</p>${key('<p>Have ready: your TradingView account and username (the indicator is shared to it), Zoom installed on a computer, and never send a password in a DM. When you pass this module the message to send is on this page and on the course map.</p>','Before the call')}`}],
 recall:rc('Risk Management','What is 1 R?',['The amount you risk on one trade: entry to stop','Your profit target','Your daily limit','The spread'],'Every ESC VLCTY result is quoted in R.'),
 steps:[['<b>Rebuild a trade.</b>',tblx(['Step','Do'],[['1','Anchor and U'],['2','Distance in U at the check'],['3','Entry, stop (fraction of U), target (multiple of stop)'],['4','Result in R']])],['<b>Rebuild another.</b>',tblx(['Part','Number'],[['Anchor','29,252.50'],['U','352'],['Distance','+0.43 U'],['Stop','45.8 pts'],['Target','91.6 pts'],['Result','+1.99 R']])]],
 explain:{prompts:['Explain what the six worked trades have in common, and what a normal losing trade looks like.'],
  ideas:['Measure from the anchor and scale by U','Entry at market on the next open; stop in at the same time','Target is a fixed multiple of the stop','Flat by the clock if neither is hit','A loss is 1 R: planned, not a mistake','Asia stops are wide so fewer contracts','Shorts are small even when they win']},
 gens:[wt,wtSize,nyCall,asiaGap],
 bank:BANKS('Worked trades',WT.map(w=>[`${w[0]}. ${w[1]} ${w[2]} How did it end?`,[`${w[3]==='target'?'Target':'Stop'}, ${w[4]}`,`${w[3]==='target'?'Stop, −1 R':'Target, +2 R'}`,'Time exit at about 0 R','It never fired'],w[5]])),
 examDesc:'Reading real ESC VLCTY trades and sizing them.'});
})();
