/* ============================================================
   FOUNDATIONS ADDITIONS for a complete beginner: a first tour of the chart, support and resistance, sessions and news,
   a demo account, and the one-trade-per-session standard.
============================================================ */
(()=>{
const f2=x=>Math.round(x*100)/100;
/* ---------- m38 · your first 20 minutes on a chart ---------- */
const candles=numGen('Candles in a window',r=>{const tf=pick(r,[1,5,15,60]),h=pick(r,[1,2,3]);return{q:`You are on the ${tf===60?'1-hour':tf+'-minute'} chart. How many candles make up ${h} hour${h>1?'s':''}?`,ans:h*60/tf,unit:'',tol:.01,why:`${h} hour${h>1?'s':''} = ${h*60} minutes. ${h*60} ÷ ${tf} = ${h*60/tf} candles.`}});
const action=r=>{const k=pick(r,[['You want to see what price did last week. What do you do?','Drag the chart to the right (or scroll back in time)','Delete the symbol','Change the account size','Close the platform'],['You want to see more candles at once on the screen. What do you do?','Zoom out (scroll or pinch)','Place an order','Change the symbol','Add a news alert'],['You want the same market on a bigger picture. What do you change?','The timeframe (for example 5-minute to 1-hour)','The broker','The stop','The contract size'],['You want to measure how many points price moved between two candles. Which tool?','The measure (ruler) tool','The text tool','The alert bell','The replay button']]);return mcq('Using the chart',k[0],[k[1],k[2],k[3],k[4]],'Scrolling, zooming, switching timeframe and measuring are the four moves you will use all the time.')};
const tfSize=r=>{const tf=pick(r,['1-minute','5-minute','1-hour','daily']);const m={'1-minute':'Each candle is one minute of trading','5-minute':'Each candle is five minutes of trading','1-hour':'Each candle is one hour of trading','daily':'Each candle is one trading day'};return mcq('Timeframe',`On the ${tf} chart, what does one candle show?`,[m[tf],...Object.values(m).filter(x=>x!==m[tf])],'The timeframe is how much time one candle covers.')};
quick({id:'m38',o:.7,ph:0,t:'Your First 20 Minutes on a Chart',out:'Move around a chart with confidence: scroll, zoom, change timeframe, measure and draw.',
 ls:['Open a chart and find your way around','Scroll through time','Zoom in and out','Change the timeframe','Measure a move','Draw a line and clean up'],
 task:'Open MNQ1! on a 5-minute chart in TradingView. Do each of these once: scroll back to yesterday, zoom out to see a full week, switch to the 1-hour chart and back, measure one move with the ruler, draw one horizontal line, then delete it.',
 learn:[
  {t:'Open a chart and find your way around',h:`<p>Open TradingView, click the search box at the top left, type <b>MNQ1!</b> and choose the continuous micro Nasdaq contract. You now have a chart. Do not worry about the buttons you do not know yet. You only need five things for now: the <b>price chart</b> in the middle, the <b>timeframe</b> buttons at the top, the <b>drawing tools</b> on the left, the <b>price scale</b> on the right and the <b>time scale</b> along the bottom.</p><p>Nothing you click on a chart can cost you money. Trading only happens when you place an order, and you will not do that for a while.</p>`},
  {t:'Scroll through time',h:`<p>The chart shows the past from left to right: the newest candle is on the right. To look further back, <b>click and drag the chart to the right</b>, or use the scroll controls. Try it now: go back one full day, then drag left to come back to the present.</p><p>Looking at old price is not wasted time. It is how you learn what the market does.</p>`},
  {t:'Zoom in and out',h:`<p><b>Scroll the mouse wheel</b> over the chart (or pinch on a trackpad) to zoom. Zooming out shows more candles, which helps you see the big picture. Zooming in shows fewer, bigger candles so you can read each one. You can also stretch the price scale up and down by dragging it.</p>${key('<p>Zoom out first to see the big picture, then zoom in to the detail. Beginners do it the other way round and miss the trend.</p>')}`},
  {t:'Change the timeframe',h:`<p>The <b>timeframe</b> is how much time one candle covers. At the top of the chart you can pick <b>1m</b> (one minute), <b>5m</b>, <b>15m</b>, <b>1h</b>, <b>4h</b> or <b>D</b> (daily). The same market looks different on each: the 1-minute chart is detailed and noisy, the daily chart is calm and shows the bigger direction.</p>${tblx(['Timeframe','One candle is','Good for'],[['1 minute','60 seconds','Precise entries'],['5 minutes','5 minutes','Day trading detail'],['1 hour','60 minutes','The trend of the day'],['Daily','One trading day','The big picture']])}`},
  {t:'Measure a move',h:`<p>The <b>measure tool</b> (a ruler icon in the left toolbar, or hold <b>Shift</b> and drag) shows how far price moved between two points: in points, in percent, and in candles. On NQ and MNQ one point is 4 ticks, so a 25-point move is 100 ticks. Use this to see how big a normal move is.</p>`},
  {t:'Draw a line and clean up',h:`<p>From the left toolbar pick the <b>horizontal line</b> and click once on the chart to place a line at a price. Click the line and press <b>Delete</b> to remove it, or use the trash can to clear everything you drew. Drawing on a chart is free and reversible, so experiment.</p><p>When you can scroll, zoom, switch timeframe, measure and draw without thinking, you are ready for the next lessons. Practise this for ten minutes, then move on.</p>`}],
 recall:rc('Market Basics','What does a price on the chart represent?',['The last level where a buyer and a seller agreed','A prediction','The fair value from the exchange','The day\'s average'],'Everything you see on a chart is made of agreed prices.'),
 steps:[['<b>The five moves.</b>',tblx(['Move','How'],[['Scroll through time','Drag the chart right'],['Zoom','Mouse wheel or pinch'],['Change timeframe','Buttons at the top'],['Measure','Ruler or Shift + drag'],['Draw','Horizontal line tool, then Delete']])],['<b>Candles in an hour.</b>',tblx(['Timeframe','Candles per hour'],[['1 minute','60'],['5 minutes','12'],['15 minutes','4'],['1 hour','1']])]],
 explain:{prompts:['Describe the five things you do on a chart in your first session, and what each one is for.'],ideas:['Search for MNQ1! to open a chart','Drag to scroll back in time; zoom with the wheel','Zoom out first for the big picture, then in for detail','The timeframe is how much time one candle covers','Measure a move with the ruler tool','Draw a horizontal line and delete it','Nothing on a chart costs money; trading only happens with an order']},
 gens:[candles,action,tfSize],
 bank:BANKS('Your first chart',[
  ['Which symbol do you search for to get the continuous micro Nasdaq chart?',['MNQ1!','AAPL','EURUSD','BTC'],'MNQ1! is the continuous micro Nasdaq-100 contract.'],
  ['Where is the newest candle on a chart?',['On the right','On the left','In the middle','At the top'],'Time runs left to right.'],
  ['How do you look at what price did in the past?',['Drag the chart to the right','Press buy','Change the account','Delete the chart'],'Dragging scrolls through time.'],
  ['What does zooming out do?',['Shows more candles at once','Places a trade','Changes the contract','Deletes drawings'],'Zoom out for the big picture.'],
  ['What is a timeframe?',['How much time one candle covers','A trading session','A prop firm rule','The length of a trade'],'1m, 5m, 1h, D.'],
  ['On the 5-minute chart, what does one candle show?',['Five minutes of trading','One hour','One day','One tick'],'Each candle is five minutes.'],
  ['Which tool measures a move in points?',['The measure (ruler) tool','The alert bell','The text tool','The replay button'],'Shift + drag also measures.'],
  ['Can drawing on a chart cost you money?',['No: only orders do','Yes, each line has a fee','Yes, if it is a trend line','Only on MNQ'],'Drawing is free and reversible.'],
  ['What should you do first: zoom in or out?',['Zoom out for the big picture, then in for detail','Zoom in as far as possible','Neither','Always stay on 1 minute'],'Big picture first.']]),
 examDesc:'Moving around a chart: timeframes, candles per window, and the five basic chart moves.'});
/* ---------- m40 · support, resistance, trend lines ---------- */
const sr=r=>{const L=pick(r,[17850,19200,21100,24500,27350]),up=r()<.5;return mcq('Support or resistance',`Price keeps stopping and turning down at ${fm(L,0)}, and it is above where price is now. What do traders call ${fm(L,0)}?`,up?['Resistance','Support','A gap','The spread']:['Resistance','Support','A tick','Margin'],'A price level where price has turned down before and sits above is resistance. Support is a level below where price has turned up.')};
const flip=r=>{const k=pick(r,[['Price breaks above a resistance level and stays above it. What often happens to that old resistance?','It can become support','It disappears forever','It becomes a gap','It becomes the spread'],['Price breaks below a support level and stays below. What often happens to that old support?','It can become resistance','It becomes a news event','It becomes volume','Nothing'],['A level has been touched four times and held each time. Compared with a level touched once, it is…','Usually more important to watch','Less important','Irrelevant','A guaranteed turn']]);return mcq('Levels',k[0],[k[1],k[2],k[3],k[4]],'Old resistance often turns into support (and the other way round). More touches make a level more visible, not a guarantee.')};
const stop=numGen('Stop past a level',r=>{const L=pick(r,[19200,21100,24500,27350]),buf=pick(r,[3,5,8,10]),long=r()<.5;return{q:`You are buying a bounce off support at ${fm(L,0)}. You put the stop ${buf} points below the level, not on it. At what price is the stop?`,ans:L-buf,unit:'',tol:.01,why:`${fm(L,0)} − ${buf} = ${fm(L-buf,0)}. Price often pokes a little past a level before it turns, so a stop exactly on the level is easily hit.`}});
quick({id:'m40',o:1,ph:0,t:'Support, Resistance & Trend Lines',out:'Mark the levels and trends every chart shows, and know what the other lines and bars on a chart are.',
 ls:['Support and resistance','Levels flip','Trends and trend lines','What the other things on a chart are','How to draw levels well','A level is a place, not a promise'],
 task:'On a 1-hour chart of MNQ1!, mark three horizontal levels where price has turned at least twice. Label each support or resistance. Then draw one trend line along at least two higher lows, or two lower highs.',
 learn:[
  {t:'Support and resistance',h:`<p><b>Support</b> is a price level where buyers have stepped in before, so price has bounced up from it. <b>Resistance</b> is a level where sellers have stepped in before, so price has turned down from it. On the chart they are simply the places where price has reversed more than once.</p>${tblx(['','What it is','Where it sits'],[['Support','Buyers stepped in','Below current price'],['Resistance','Sellers stepped in','Above current price']])}<p>They are not exact lines. Think of them as zones a few points wide.</p>`},
  {t:'Levels flip',h:`<p>When price breaks <b>through</b> a level and holds on the other side, the level often <b>flips its role</b>: old resistance can become support, and old support can become resistance. This is one of the most common things you will see on any chart.</p><p>Later in this course you will learn the version professionals use: highs and lows as pools of orders (<b>liquidity</b>), and gaps and structure. Support and resistance is the plain-language starting point.</p>`},
  {t:'Trends and trend lines',h:`<p>A <b>trend</b> is a sequence of higher highs and higher lows (an uptrend) or lower highs and lower lows (a downtrend). A <b>trend line</b> is a sloping line you draw along at least two of those lows (in an uptrend) or highs (in a downtrend). When price stops respecting the line, the trend may be changing.</p><p>No trend, a sideways range, is also a market state. Many beginners lose money by assuming there is always a trend.</p>`},
  {t:'What the other things on a chart are',h:`<p>You will see other traders' charts covered in extras. Here is what they usually are, and none of them is required:</p>${tblx(['Thing','What it shows'],[['Volume bars','How many contracts traded in each candle'],['Moving average','The average price over the last N candles, drawn as a smooth line'],['RSI, MACD and similar','Indicators built from price: they summarise momentum'],['Vertical lines','Session opens or news times'],['Colored boxes','A trader marking a zone they care about']])}<p>This course reads price directly: levels, structure, gaps and timing. You can ignore most extras until you know why you want one.</p>`},
  {t:'How to draw levels well',h:`<ul><li>Start on a <b>higher timeframe</b> (1-hour or 4-hour) and mark the obvious levels first.</li><li>Use <b>zones</b>, a few points wide, not hair-thin lines.</li><li>Mark only the levels price has <b>reacted to more than once</b>. Too many lines make the chart useless.</li><li>Place a stop <b>past</b> a level, not on it: price often pokes through a little before turning.</li></ul>`},
  {t:'A level is a place, not a promise',h:key('<p>A support or resistance level is a place where price <b>may</b> react. Sometimes it holds and sometimes it breaks, and you will not know which in advance. That is exactly why every trade needs a stop. The rest of this course teaches how to tell the better places from the worse ones.</p>')}],
 recall:rc('Your First 20 Minutes on a Chart','How do you look at what price did in the past?',['Drag the chart to the right','Press buy','Change the account','Delete the chart'],'You scroll through time by dragging.'),
 steps:[['<b>Support and resistance.</b>',tblx(['Level','Role','Seen as'],[['19,200','Support','Price bounced up twice'],['19,500','Resistance','Price turned down twice']])],['<b>A stop past the level.</b>',tblx(['Item','Number'],[['Support level','19,200'],['Stop','8 points below: 19,192']])]],
 explain:{prompts:['Explain support and resistance, how a level can flip, and why a stop goes past a level.'],ideas:['Support is where buyers stepped in before; resistance is where sellers did','Levels are zones, a few points wide','Old resistance can become support after a break, and the reverse','A trend is higher highs and higher lows (or the reverse)','A trend line connects two or more lows or highs','Most extras on charts are optional','A level is a place price may react, not a promise','Put the stop past the level, not on it']},
 gens:[sr,flip,stop],
 bank:BANKS('Levels and trends',[
  ['What is support?',['A level where buyers stepped in before','A level where sellers stepped in','The highest price of the day','A type of order'],'Support sits below price.'],
  ['What is resistance?',['A level where sellers stepped in before','A level where buyers stepped in','The opening price','A news time'],'Resistance sits above price.'],
  ['What often happens to old resistance after price breaks above it and holds?',['It can become support','It vanishes','It becomes a gap','It becomes the stop'],'Levels flip.'],
  ['What makes an uptrend?',['Higher highs and higher lows','Lower lows','A sideways line','Rising volume'],'The sequence of swings defines the trend.'],
  ['What is a trend line?',['A line drawn along two or more lows (or highs)','The daily open','The spread','A stop'],'It follows the slope of the trend.'],
  ['Why are levels drawn as zones, not exact lines?',['Price often reacts a few points either side','Lines are expensive','Zones are required by brokers','Because NQ has no ticks'],'Levels are approximate.'],
  ['Where does the stop go on a bounce off support?',['A little below the level, not on it','Exactly on the level','Above the level','Nowhere'],'Price often pokes through before turning.'],
  ['What does volume show?',['How many contracts traded','The direction','The trend','The spread'],'It is the amount traded.'],
  ['Is a level a guarantee that price will turn?',['No: it is a place price may react','Yes','Only on 5 minutes','Only with volume'],'Every trade still needs a stop.']]),
 examDesc:'Support, resistance, role flips, trends, stops past levels and what the other chart tools are.'});
/* ---------- m41 · sessions and news ---------- */
const newsTime=r=>{const k=pick(r,[['The monthly jobs report (non-farm payrolls) usually comes out at what time New York time?','8:30 AM','4:00 PM','2:00 AM','6:00 PM','The big economic reports are mostly at 8:30 AM.'],['The weekly jobless claims report comes out at…','8:30 AM on Thursdays','4:00 PM on Fridays','6:00 PM on Sundays','Midnight','Jobless claims are 8:30 AM Thursdays.'],['The Federal Reserve rate decision is usually announced at…','2:00 PM','8:30 AM','6:00 PM','Midnight','The statement is at 2:00 PM; the press conference follows.']]);return mcq('News times',k[0],[k[1],k[2],k[3],k[4]],k[5])};
const wide=numGen('A wider spread',r=>{const a=pick(r,[1,2]),b=pick(r,[4,6,8]),mn=r()<.5,tv=mn?.5:5;return{q:`Around a big news release the NQ spread widens from ${a} tick${a>1?'s':''} to ${b} ticks. On 1 ${mn?'MNQ':'NQ'} (tick = $${tv}), how much more does a round trip at the market cost because of the wider spread? (A round trip crosses the spread once.)`,ans:(b-a)*tv,unit:'$',tol:.01,why:`(${b} − ${a}) ticks × $${tv} = $${(b-a)*tv}. And that is before the extra slippage on your stop in a fast move.`}});
const newsRule=r=>{const k=pick(r,[['A major report is due in five minutes and you are flat. What is the sensible beginner rule?','Stand aside until after the release has settled','Place a big trade just before','Move your stop wider','Double your size'],['You are in a trade and a major report is due in a minute. Your plan says to…','Decide in advance: close, reduce, or accept the risk with a stop','Remove the stop','Add contracts','Ignore the calendar'],['Why do prices jump around news?','Many orders hit at once and the market reprices quickly','The exchange sets the price','Brokers close the market','Charts glitch','Fast repricing and thin liquidity move price in jumps']]);return mcq('News rules',k[0],[k[1],k[2],k[3],k[4]],'Spreads widen and stops slip around big releases, so you plan for it ahead of time.')};
quick({id:'m41',o:1.1,ph:0,t:'Sessions & Economic News',out:'Know when the market is busy, when big news lands, and what to do about it.',
 ls:['The three sessions','Why price moves at certain times','Scheduled economic news','What happens to price around news','Your plan for news days'],
 task:'Open an economic calendar for this week. Write down the three biggest scheduled releases (name, day, time in New York time). Mark each on your chart as a vertical line and watch what the market did around it in replay.',
 learn:[
  {t:'The three sessions',h:`<p>NQ trades almost all day, but it is not equally busy. In New York time:</p>${tblx(['Session','Time (ET)','What it is like'],[['Asia','6:00 PM – 3:00 AM','Quieter, thinner'],['London','3:00 AM – 8:30 AM','Busier as Europe opens'],['New York','8:30 AM – 4:00 PM','The busiest: the stock market and big news'],['Daily break','5:00–6:00 PM','NQ is closed']])}<p>Different sessions behave differently, and later modules show how.</p>`},
  {t:'Why price moves at certain times',h:`<p>Price tends to move more when more people are trading. The <b>New York open at 9:30 AM</b> is when the stock market opens, and activity jumps. The hour after it is usually the busiest of the day. Quiet periods, such as lunchtime, tend to have smaller moves.</p><p>Time of day is one of the simplest and most useful things a beginner can learn: do not treat every hour the same.</p>`},
  {t:'Scheduled economic news',h:`<p>Governments and central banks publish numbers on a schedule: inflation, jobs, interest rates. The market reprices quickly when the numbers surprise people. Most are released at <b>8:30 AM New York time</b>:</p>${tblx(['Event','When','Why it matters'],[['Jobs report (non-farm payrolls)','First Friday of the month, 8:30 AM','Shows the health of the economy'],['Inflation (CPI)','Monthly, 8:30 AM','Drives expectations for interest rates'],['Jobless claims','Thursdays, 8:30 AM','A weekly read on jobs'],['Federal Reserve rate decision','About 8 times a year, 2:00 PM','Sets the rate and the tone']])}<p>An <b>economic calendar</b> lists them all. Check it every morning.</p>`},
  {t:'What happens to price around news',h:`<p>Right around a big release, many orders hit at once. The price can jump several points in a second, the <b>spread widens</b>, and your stop can fill much further away than you set it (<b>slippage</b>). A candle can look huge and then reverse.</p>${warn('<p>A stop loss is not a guarantee of the exact price in a fast market. Around news it can fill worse, which is one more reason to keep size small.</p>')}`},
  {t:'Your plan for news days',h:`<p>Decide the night before, in writing, what you will do on a news day:</p><ul><li><b>Stand aside</b> for a few minutes before and after the release and trade once the market has settled.</li><li><b>Trade smaller</b> on big news days.</li><li>If you already hold a trade, decide in advance whether to <b>close, reduce or accept the risk</b>.</li></ul><p>Some systems are tested through news and trade it by default, others skip it. Whatever your plan is, know it before the release, not during it.</p>`}],
 recall:rc('How Futures & NQ Work','When does NQ close for its daily break?',['5:00 to 6:00 PM ET','9:30 to 10:00 AM ET','Midnight','4:00 PM'],'The daily break is the only time NQ is closed.'),
 steps:[['<b>The week\'s calendar.</b>',tblx(['Day','Time (ET)','Event'],[['Thursday','8:30 AM','Jobless claims'],['Friday','8:30 AM','Jobs report'],['Wednesday','2:00 PM','Fed decision (on rate weeks)']])],['<b>What widens.</b>',tblx(['Item','Normal','At news'],[['NQ spread','1 tick','4–8 ticks'],['Stop fill','at the stop','can be worse']])]],
 explain:{prompts:['Explain why news days are riskier and what your plan for them is.'],ideas:['Asia is quieter, London busier, New York the busiest','Activity jumps at the 9:30 AM New York open','Major reports are mostly at 8:30 AM ET; the Fed at 2:00 PM','Prices reprice in jumps around news','The spread widens and stops can slip','Check an economic calendar every morning','Decide the news plan the night before: stand aside, trade smaller, or know your position plan','A stop is not a guaranteed price in a fast market']},
 gens:[newsTime,wide,newsRule],
 bank:BANKS('Sessions and news',[
  ['Which session is usually the busiest for NQ?',['New York','Asia','The daily break','London lunchtime'],'The stock market open drives activity.'],
  ['What time is the New York stock market open?',['9:30 AM ET','8:30 AM ET','6:00 PM ET','4:00 PM ET'],'9:30 AM New York time.'],
  ['When are most major US economic reports released?',['8:30 AM ET','4:00 PM ET','6:00 PM ET','Midnight'],'8:30 AM is the standard.'],
  ['What is an economic calendar for?',['Seeing when scheduled news will be released','Placing orders','Measuring candles','Setting stops'],'You check it every morning.'],
  ['What usually happens to the spread around big news?',['It widens','It disappears','It stays the same','It becomes negative'],'Thin, fast markets have wider spreads.'],
  ['Can a stop fill worse than the price you set?',['Yes, in a fast market (slippage)','No, never','Only with limit orders','Only on MNQ'],'Slippage is real.'],
  ['What is a sensible beginner approach to a big news release?',['Stand aside until it has settled, or trade much smaller','Go all in','Remove the stop','Trade without checking'],'Plan for it in advance.'],
  ['When should you decide your plan for news days?',['Before the release, ideally the night before','During the release','After the release','Never'],'Decide calmly in advance.'],
  ['When does NQ take its daily break?',['5:00 to 6:00 PM ET','9:30 to 10:30 AM ET','Midnight','3:00 AM'],'The only closed hour.']]),
 examDesc:'Sessions, the busiest times, scheduled news, what news does to spreads and stops, and a news-day plan.'});
/* ---------- m39 · demo account ---------- */
const startBal=numGen('Demo balance',r=>{const b=pick(r,[25000,50000,100000]),p=pick(r,[120,250,400,640]),w=r()<.6;return{q:`Your demo account starts at $${fm(b,0)}. You make a trade and ${w?'win':'lose'} $${p}. What is the balance now?`,ans:w?b+p:b-p,unit:'$',tol:.5,why:`$${fm(b,0)} ${w?'+':'−'} $${p} = $${fm(w?b+p:b-p,0)}.`}});
const riskAmt=numGen('One percent risk',r=>{const b=pick(r,[25000,50000,100000]),pc=pick(r,[.5,1,2]);return{q:`Your demo balance is $${fm(b,0)}. How many dollars is ${pc}% of it?`,ans:b*pc/100,unit:'$',tol:.5,why:`$${fm(b,0)} × ${pc}% = $${fm(b*pc/100,0)}. A common size of risk per trade is a small fraction of the account.`}});
const demoWhy=r=>{const k=pick(r,[['Why practise on a demo account first?',['You learn the platform and your own habits with no real money at risk','It always makes money','Brokers pay you to use it','It has no rules'],'A demo is for learning.'],['What is the limit of a demo account?',['It cannot show how it feels to risk real money','It cannot place orders','It has no charts','It costs more'],'Fear and greed only show up with real money.']]);return mcq('Demo account',k[0],k[1],k[2])};
quick({id:'m39',o:1.3,ph:0,t:'Your Demo Account: Open It and Use It',out:'Open a demo account, place a practice order with a stop and target, and read your balance.',
 ls:['Why a demo account','Opening a paper account','Placing your first practice order','Reading the account panel','The rules for demo trading','From demo to real'],
 task:'Open a demo (paper) account. Place one MNQ practice trade with a stop loss and a target, let it close, and write down the balance before and after, and the reason you took it.',
 learn:[
  {t:'Why a demo account',h:`<p>A <b>demo</b> (or <b>paper</b>) account is a practice account: real prices, pretend money. You can place orders, win and lose, and see exactly how an account behaves, without risking a dollar. It is where you make your first mistakes cheaply.</p><p>The limit: it cannot show how it feels to lose real money. That comes later, in small size.</p>`},
  {t:'Opening a paper account',h:`<p>On TradingView, open the <b>Trading Panel</b> at the bottom of the chart and choose <b>Paper Trading</b>, then connect it. You get a practice account with a starting balance that you can reset. Other platforms and prop firms also offer simulated accounts, and an evaluation account is a kind of demo with rules.</p>${warn('<p>Menus and which markets are included change over time, and real-time data for some futures can need a market-data subscription. If something looks different or is unavailable, check the platform\'s current help pages, or ask in the community.</p>','Check before you rely on it')}`},
  {t:'Placing your first practice order',h:`<p>In the panel pick the symbol (<b>MNQ</b>), the number of <b>contracts</b> (start with 1), the side (<b>buy</b> for long, <b>sell</b> for short), and set a <b>stop loss</b> and a <b>take profit</b> so the trade is protected. This is a <b>bracket</b>: an entry with a stop and a target. You will learn orders properly in the next module. For now place one small trade and watch it.</p>${key('<p>Every practice trade gets a stop and a target, exactly as you would with real money. Practise the habit now.</p>')}`},
  {t:'Reading the account panel',h:`<p>The panel shows the numbers that matter: your <b>balance</b> (your money after closed trades), <b>open profit and loss</b> (the live result of the trade you are in), and your <b>position</b> (what you hold). When a stop or target is hit, the trade closes and the balance updates. Look at the balance before and after every trade.</p>`},
  {t:'The rules for demo trading',h:`<ul><li><b>Treat it as real.</b> Trade the size you could actually afford to lose.</li><li><b>Log every trade</b>: why you took it, the stop, the target, the result.</li><li><b>Use a stop on every trade.</b></li><li><b>Do not reset the account</b> just because you lost: look at why.</li><li>Take <b>one trade per session</b> (the next module explains why).</li></ul>`},
  {t:'From demo to real',h:`<p>When you are comfortable and following your plan on demo, the usual path is: keep going on demo until your habits are steady, then a <b>prop-firm evaluation</b> or a small live account on <b>micro</b> contracts. The school's later modules and the Eval lab help you rehearse that step. Never rush it: skill comes first.</p>`}],
 recall:rc('Orders & Your First Trade','What is a bracket order?',['An entry with a stop and a target attached','A market order only','A type of chart','A fee'],'Your practice orders should always be brackets.'),
 steps:[['<b>Before and after.</b>',tblx(['Item','Number'],[['Starting balance','$50,000'],['Trade: 1 MNQ, 20-point target hit','+$40'],['Balance','$50,040']])],['<b>Size a practice trade.</b>',tblx(['Item','Number'],[['Balance','$50,000'],['Risk 1%','$500'],['Stop 25 pts on MNQ','$50 per contract'],['Contracts','1 to start']])]],
 explain:{prompts:['Explain what a demo account is for, how to place a practice order, and the rules you will follow on it.'],ideas:['A demo account uses real prices and pretend money','It lets you learn the platform and your own habits for free','Open Paper Trading from the Trading Panel (menus may change)','Place a bracket: entry, stop, target','Read the balance, open P&L and position','Treat it as real: log trades, always use a stop','Do not reset after a loss: learn from it','It cannot teach how real money feels, so go to micro size next']},
 gens:[startBal,riskAmt,demoWhy],
 bank:BANKS('Demo account',[
  ['What is a demo (paper) account?',['An account with real prices and pretend money','An account with real money and no risk','A prop firm payout','A tax account'],'Practice only.'],
  ['What is a demo account good for?',['Learning the platform and your habits without risk','Getting paid','Avoiding stops','Replacing a plan'],'It is a classroom.'],
  ['Where do you find Paper Trading on TradingView?',['The Trading Panel at the bottom of the chart','The news page','The settings of the candles','The alert list'],'Menus may change, so check the help pages.'],
  ['What should every practice trade have?',['A stop loss and a target','Only a target','Nothing','A large size'],'Build the habit now.'],
  ['What does the balance show?',['Your money after closed trades','The next price','The spread','Your open stop'],'It changes when trades close.'],
  ['What is open P&L?',['The live profit or loss of the trade you are in','The balance','The fees','The target'],'It moves with price.'],
  ['What is the main limit of a demo account?',['It cannot show how real money feels','It has no charts','It is slow','It has no orders'],'Emotions only come with real risk.'],
  ['Should you reset the demo after a loss?',['No: look at why you lost','Yes, always','Only on Fridays','Yes, and double size'],'Learn from it.'],
  ['What is the usual path after demo?',['Micro size or a prop evaluation, only when habits are steady','Full-size NQ immediately','Stopping','A bigger demo'],'Skill first.']]),
 examDesc:'Opening a demo, a bracket practice order, reading the account panel and the demo rules.'});
/* ---------- m42 · one trade per session ---------- */
const sessions=r=>{const k=pick(r,[['You took your one New York trade and it lost at 10:05 AM. Your rule is one trade per session. What now?','You are done for the New York session; review it and come back for the next session','Take another trade right away to win it back','Double the size','Remove the stop'],['Your Asia trade hit its target at 9 PM. It is 9:30 PM and there is a new setup. What does the rule say?','No more trades in the Asia session','Take it, you are winning','Take it with a bigger size','Take it without a stop'],['It is 11:00 AM New York time and your New York trade won. You see another setup at 2:00 PM. What does the rule say?','No: one trade per session, and New York is done','Yes, trade it','Yes, if it is bigger','Yes, with no stop']]);return mcq('One trade per session',k[0],[k[1],k[2],k[3],k[4]],'The standard is one trade per session. Win or lose, once your trade is done you are finished with that session.')};
const day=numGen('The most a day can cost',r=>{const s=pick(r,[1,2,3]),risk=pick(r,[100,200,300,500]);return{q:`You trade ${s} session${s>1?'s':''} today and risk $${risk} on your one trade in each. If every trade is stopped out, what is the most you lose on the day (ignore costs)?`,ans:s*risk,unit:'$',tol:.01,why:`${s} trade${s>1?'s':''} × $${risk} = $${s*risk}. One trade per session puts a ceiling on a bad day.`}});
const revenge=r=>{const k=pick(r,[['After a loss you feel the urge to take another trade immediately. What is that called?','Revenge trading','Risk management','Hedging','A plan'],['Taking many small trades because you are bored or want action is called…','Overtrading','Scaling','Patience','Journaling']]);return mcq('Overtrading',k[0],[k[1],k[2],k[3],k[4]],'Both come from emotion, not from a setup in your plan.')};
quick({id:'m42',o:1.4,ph:0,t:'One Trade Per Session',out:'Follow the one-trade-per-session standard and know why it protects you.',
 ls:['The standard: one trade per session','Why fewer trades is better','Revenge trading and overtrading','What counts as a session','Your daily loss limit','Making it a habit'],
 task:'For the next five trading days, write down the sessions you will trade, and take at most one trade in each. If you want to break the rule, write the reason in your journal first and then do not take the trade.',
 learn:[
  {t:'The standard: one trade per session',h:`<p>The standard taught in this school is <b>one trade per session</b>. You wait for your setup, take it once with a stop and a target, and when that trade is over, <b>win or lose, you are finished with that session</b>. You may trade the next session if you have one in your plan.</p>${key('<p>One trade per session. Not "until I win" and not "one more". A single clear trade is a decision. Several in a row are a mood.</p>')}`},
  {t:'Why fewer trades is better',h:`<ul><li><b>Quality over quantity.</b> You only get one, so you wait for your best setup instead of the first one.</li><li><b>Risk is capped.</b> A bad day is a few planned losses, not a spiral.</li><li><b>Costs stay small.</b> Fees and slippage are charged on every trade.</li><li><b>You can review it.</b> One trade a session is easy to journal and learn from.</li><li><b>It fits prop-firm rules.</b> Daily loss limits and consistency rules reward steady, planned trading.</li></ul>`},
  {t:'Revenge trading and overtrading',h:`<p><b>Revenge trading</b> is taking another trade right after a loss to win the money back. <b>Overtrading</b> is taking many trades because you are bored, excited or afraid to miss out. Both come from emotion, not from a setup, and both are among the fastest ways to lose an account. The one-trade-per-session rule blocks both on purpose.</p>${warn('<p>If you catch yourself looking for "just one more" trade, close the platform for the session. That urge is the signal to stop.</p>')}`},
  {t:'What counts as a session',h:`<p>A <b>session</b> is a block of the trading day. In New York time: <b>Asia</b> (6:00 PM to 3:00 AM), <b>London</b> (3:00 AM to 8:30 AM) and <b>New York</b> (8:30 AM to 4:00 PM). A new session means a new decision: one trade in each session you choose to trade, not one trade in every hour.</p><p>Most traders choose one or two sessions and master them, instead of trading all day and all night.</p>`},
  {t:'Your daily loss limit',h:`<p>On top of the one-trade rule, set a <b>daily loss limit</b>: the most you will lose in a day, in dollars. Prop firms have their own hard daily limits, so yours should be smaller. If you reach it, you are done for the day, no matter what the chart does. With one trade per session and a fixed risk, your worst day is easy to calculate in advance.</p>`},
  {t:'Making it a habit',h:`<ol><li>Write down which sessions you will trade tomorrow.</li><li>For each, write what setup you are waiting for.</li><li>When your trade is done, close the chart for that session.</li><li>Journal it in two minutes: the setup, the result, whether you followed the rules.</li></ol><p>Following the rule is a win, even when the trade loses.</p>`}],
 recall:rc('Your Demo Account: Open It and Use It','What should every practice trade have?',['A stop loss and a target','Only a target','Nothing','A large size'],'The same rules apply on demo and with real money.'),
 steps:[['<b>A day on the rule.</b>',tblx(['Session','Trades','Why'],[['Asia','1 at most','One decision a night'],['London','1 at most, if you trade it','Only if it is in your plan'],['New York','1 at most','Win or lose, you are done']])],['<b>The cost of a bad day.</b>',tblx(['Item','Number'],[['Risk per trade','$200'],['Sessions traded','2'],['Worst day (both stopped)','$400']])]],
 explain:{prompts:['Explain the one-trade-per-session rule, why it protects you, and what to do when you want to break it.'],ideas:['One trade per session, win or lose','You then finish that session','It blocks revenge trading and overtrading','It caps the cost of a bad day','Fees and slippage stay small','It makes your trades easy to journal','A session is Asia, London or New York','Keep a daily loss limit below the firm\'s limit','If you want one more, close the chart']},
 gens:[sessions,day,revenge],
 bank:BANKS('One trade per session',[
  ['How many trades per session does the school teach?',['One','As many as you like','Three','Until you win'],'One trade per session.'],
  ['You win your trade in a session. What now?',['You are done for that session','Take another','Double size','Remove the stop'],'The rule does not depend on the result.'],
  ['You lose your trade in a session. What now?',['You are done for that session and you review it','Take revenge','Double size','Skip the stop'],'No revenge trade.'],
  ['What is revenge trading?',['Trading again right after a loss to win it back','A planned second trade','A hedge','A new setup'],'It comes from emotion.'],
  ['What is overtrading?',['Taking many trades from boredom or fear of missing out','Trading one session','Using a stop','Journaling'],'Quantity over quality.'],
  ['Which is one benefit of one trade per session?',['A bad day has a limited cost','More fees','More stress','Bigger size'],'The ceiling is easy to calculate.'],
  ['What is a session?',['A block of the trading day, such as Asia, London or New York','One hour','One candle','One week'],'Sessions in New York time.'],
  ['What should your own daily loss limit be compared with the firm\'s?',['Smaller','Bigger','The same','Not needed'],'Stay inside the firm\'s limit.'],
  ['What do you do when you want "just one more"?',['Close the platform for the session','Take it','Add size','Widen the stop'],'That urge is the signal to stop.']]),
 examDesc:'The one-trade-per-session standard, why it protects you, revenge trading, overtrading and daily limits.'});
})();
