/* ---------- 26 · PO3 in Asia ---------- */
(()=>{
const ny=r=>{const big=r()<.5;return mcq('Filter 1',big?'New York made a big move today (500+ points). What do you expect from Asia?':'New York chopped and took no big highs or lows. What do you expect from Asia?',big?['Asia is likely to chop: skip it','Asia is the clean session: trade it','It does not matter','Always trade Asia']:['Asia is likely the clean session: look for trades','Asia will chop: skip it','It does not matter','Skip it'],big?'Sessions take turns. After a big New York expansion Asia tends to chop, so skip it.':'NY accumulated, so Asia is next in line to manipulate and deliver.')};
const gaps=r=>{const ok=r()<.5;return mcq('Filter 2',ok?'On the 5-minute chart fair value gaps are forming and price dips into them, holds and bounces. What does that say?':'On the 5-minute chart price slices back and forth through gaps in both directions ("barcode"). What does that say?',ok?['Both filters can pass: gaps are respected, so trade Asia','Skip: it is chop','Short the next gap','Nothing'] :['Chop: do not trade Asia today','Gaps are respected: trade it','Buy every gap','Nothing'],ok?'Gaps forming and holding means real direction.':'Barcode chop means no direction, so Asia is skipped.')};
const candle=r=>{const long=r()<.5;return{kind:'order',topic:'The 8 PM candle',q:`Put the 8 PM hour candle's path in order for a ${long?'long':'short'}.`,steps:long?['Open','Low (dip into your key level: the manipulation)','High (drive up: the distribution)','Close']:['Open','High (push into your key level: the manipulation)','Low (drive down: the distribution)','Close'],why:long?'For a long you want Open → Low → High → Close (OLHC): dip first, then drive up.':'For a short you want Open → High → Low → Close (OHLC): push up first, then drive down.'}};
const target=numGen('Target',r=>{const s=pick(r,[8,10,12.5,15]),k=pick(r,[1,2,3]);return{q:`In Asia you risk ${s} points. What is the target in points for a ${k}:1 reward-to-risk (the default is 1:1, the maximum 1:3)?`,ans:s*k,unit:'pts',tol:.01,why:`${s} × ${k} = ${s*k} points. Asia defaults to 1:1 and caps a single trade at 1:3.`}});
quick({id:'m26',o:18.5,ph:6,t:'PO3 in Asia (8 PM–12 AM)',out:'Run the Power of Three on the Asia session, after two filters.',
 ls:['Filter 1: what did New York do?','Filter 2: are gaps respected?','The draw and a key level','The 8 PM candle','IFG confirmation, stop and target','One win or two losses and you are done'],
 task:'Open your last five Asia sessions in Bar Replay. For each, note what New York did that day, whether 5m gaps were respected, where the draw and the key level were, and what the 8 PM candle did (OLHC or OHLC). Mark the IFG close and measure the 1:1.',
 learn:[
  {t:'Asia is not clean every day',h:`<p>The Asia session runs <b>8:00 PM to 12:00 AM ET</b>. It is not clean every day, so the model starts with <b>two filters</b> before it looks for an entry. Most Asia losses come from trading it on the wrong days.</p>`},
  {t:'Filter 1: what did New York do?',h:`<p>Sessions take turns. If New York chopped and took no big highs or lows, Asia is likely the clean session. If New York already made a big move (500+ points), Asia tends to chop: skip it.</p>`},
  {t:'Filter 2: are gaps respected?',h:`<p>On the 5m you want fair value gaps <b>forming</b> and price <b>reacting</b> off them, not slicing back and forth through them ("barcode" chop). Gaps forming and holding means real direction.</p>`},
  {t:'The draw and the key level',h:`<p><b>Step 1:</b> the draw: a target on the 4H or daily. The <b>new week opening gap</b> is the highest priority. <b>Step 2:</b> a key level that lines up with that draw: somewhere price can dip into before going up (a bullish gap below, for a long).</p>`},
  {t:'The 8 PM candle and the entry',h:`<p>For a long you want the 8 PM candle to go <b>Open → Low → High → Close (OLHC)</b>: dip into your key level first, then drive up. For a short, OHLC. Touching the level is not confirmation: wait for a close back <b>through</b> the small gap the drop left (an <b>IFG</b>). That is the green light.</p>`},
  {t:'Stop, target and the daily rule',h:`<p>The stop goes at the swing low (for a long). <b>Default 1:1, maximum 1:3.</b> Risk 1% a trade. <b>One win = done. Two losses = done.</b></p>`}],
 recall:rc('Range, Sweep, Reversal (H/L · NY ATM)','In H/L, what do you do if the cutoff passes with no sweep?',['No trade: that is the model working','Trade the middle','Buy the open','Force one'],'The same discipline applies in Asia.'),
 steps:[['<b>Two filters first.</b>',tblx(['Filter','Pass','Fail'],[['New York','Chopped, no big move','Expanded 500+ points'],['Gaps','Forming and respected','Barcode chop']])],['<b>The path of a long.</b>',tblx(['Step','What happens'],[['1','Draw: the new week opening gap above'],['2','Key level: a bullish gap below'],['3','8 PM candle dips in (OLHC)'],['4','IFG closes back through: enter'],['5','Stop at the swing low, 1:1 default']])]],
 explain:{prompts:['Explain the two filters that decide whether you trade the Asia session at all, and why they come first.','Walk through an Asia long from the draw to the stop and target.'],
  ideas:['Asia runs 8 PM to 12 AM ET and is not clean every day','Filter 1: if New York chopped, Asia is likely clean; after a big NY move, skip','Filter 2: gaps forming and respected, not barcode chop','The draw is the new week opening gap or another higher-timeframe target','The key level lines up with the draw','8 PM candle: OLHC for longs, OHLC for shorts','Wait for the IFG close, not a touch of the level','Default 1:1, max 1:3; one win or two losses and you are done']},
 gens:[ny,gaps,candle,target],
 bank:BANKS('Asia',[
  ['ASIAFLOW PO3 uses…',['Filters, a key level and the 8 PM candle','The NY open only','London only','No filters'],'Two filters, then draw, key level, 8 PM candle, IFG.'],
  ['The Asia session runs…',['8:00 PM to 12:00 AM ET','6 AM to 9 AM ET','9:30 AM to 4 PM ET','5 PM to 6 PM ET'],'Asia is 8 PM to midnight in this model.'],
  ['Touching the key level means…',['Nothing yet: wait for the IFG close','Enter now','The trade is over','Double the size'],'Levels break. Confirmation first.'],
  ['The highest-priority draw in Asia is…',['The new week opening gap','The 1m wick','A round number','Yesterday\'s close'],'Opening gaps are king.'],
  ['The Asia stop for a long goes…',['At the swing low','At the draw','At the open','Nowhere'],'The manipulation low.'],
  ['What is the default Asia target?',['1:1, up to 1:3','Always 1:3','Always the full gap','None'],'Default 1:1, max 1:3.'],
  ['After one win in Asia you…',['Are done','Take another','Double size','Remove the stop'],'One win = done. Two losses = done.'],
  ['A "barcode" 5m chart means…',['Skip Asia: gaps are not respected','Trade every gap','Short the high','Nothing'],'No direction, no trade.']]),
 examDesc:'The two Asia filters, the 8 PM candle path, the IFG entry and Asia targets.'});
})();

/* ---------- 27–30 · ECHO X ORBIT ---------- */
(()=>{
const draw=numGen('The draw',r=>{const s=pick(r,[10,12,14,15,18,20]),d=pick(r,[16,22,28,35,40,48]);return{q:`Your stop is ${s} points and the nearest draw on liquidity is ${d} points away. How many times the stop is the draw (one decimal)?`,ans:Math.round(d/s*10)/10,unit:'×',tol:.06,why:`${d} ÷ ${s} = ${Math.round(d/s*10)/10}×. ${d/s>=2?'It is at least 2×, so the draw is valid.':'It is under 2×, so no trade: no valid draw.'}`}});
const minDraw=numGen('The 2× rule',r=>{const s=pick(r,[10,12,15,18,20]);return{q:`Stop is ${s} points. What is the minimum distance to the draw for a valid ECHO X ORBIT trade, in points?`,ans:2*s,unit:'pts',tol:.01,why:`2 × ${s} = ${2*s} points.`}});
const valid=r=>{const s=pick(r,[12,14,15,16]),d=pick(r,[18,22,32,40,45]),ok=d>=2*s,trend=r()<.75;
  return mcq('Valid or not?',`A clean Echo: sweep, CISD, rejection block inside the FVG. Stop ${s} points, nearest draw ${d} points away, and it is ${trend?'with':'against'} the 4H trend. Take it?`,trend&&ok?['Yes: with the trend and a valid draw','No: skip it','Only with double size','Only on Fridays']:['No: skip it','Yes: it is a clean setup','Yes, with a wider stop','Yes, with a bigger target'],trend&&ok?`The draw is ${d/s>=2?(Math.round(d/s*10)/10):''}× the stop and the setup is with the 4H trend: both conditions pass.`:!ok?`The draw is only ${Math.round(d/s*10)/10}× the stop, under 2×. Every other box can be ticked and this one rule still says no.`:'Against the 4H trend is where the edge leaks away. Wait for a setup with the trend.');};
const engine=r=>{const e=pick(r,[['Sweep a low, CISD, then a rejection block inside the FVG','Echo'],['A big swing, a fib, the 0.62–0.79 zone, an inversion on the leg in','Orbit']]);return mcq('Which engine?',`Which engine is this? "${e[0]}."`,e[1]==='Echo'?['Echo','Orbit','Both','Neither']:['Orbit','Echo','Both','Neither'],'Echo = sweep, CISD, rejection block inside an FVG. Orbit = big swing, fib, OTE zone, inversion on the leg in.')};
const SH=['Sweep an old low','Close back above the open of the down-move (the CISD)','Price returns into the FVG and is rejected (the RB)','Enter, with the stop past the wick and the target at the draw'];
const echoOrder=()=>({kind:'order',topic:'Echo',q:'Put the Echo steps in order.',steps:SH,why:'Sweep → CISD → return to the FVG and rejection block → entry. A sweep alone is not an entry.'});
const OS=['Mark the big, obvious swing','Draw the fib from the swing low to the swing high','Wait for price to reach the 0.62–0.79 zone (OTE)','Wait for the inversion of the gap on the leg in','Enter, with the stop under the leg-in low and the target at the draw'];
const orbitOrder=()=>({kind:'order',topic:'Orbit',q:'Put the Orbit steps in order.',steps:OS,why:'Big swing → fib → OTE reached → inversion → entry. Orbit tells you where; the confirmation tells you when.'});
const A=(m)=>m;
const replay=r=>{const k=pick(r,[
 ['Price just ran above the old high. Short now?',['No: a sweep alone is not an entry; wait for the CISD','Yes, short the sweep','Buy the breakout','Add size'],'Without a CISD the high can keep running.'],
 ['A big red candle closed below the open of the up-move and left a gap. What is it?',['A CISD with an FVG: the Echo is forming','Nothing important','A reason to short at market at once','A news candle'],'Now wait for price to return into the gap.'],
 ['Price pushed back into the FVG and left a long upper wick. The draw below is well over 2× your stop. Your move?',['Short from the rejection block, stop above it','Skip, it is too late','Short with no stop','Short at double size'],'RB inside the FVG with a valid draw is the Echo entry.'],
 ['Sweep, CISD and rejection block inside the FVG are all there. The only liquidity in your direction is 16 points away and your stop is 15. Take it?',['No: the draw is about 1× the stop, not 2×','Yes: everything else lines up','Yes, with a bigger target','Yes, with a wider stop'],'No valid draw, no trade.'],
 ['Price is in the OTE zone but nothing has inverted yet.',['Wait for the inversion','Buy now','Short it','Move the fib'],'The inversion is your sign the leg in is finished.'],
 ['The pullback only reaches the 0.38 level. Orbit?',['No: it has not reached OTE','Yes','Only with ES','Yes, at half size'],'Orbit wants the deep pullback.']]);return mcq('Make the call',k[0],k[1],k[2])};
const common=(id,o,ph,t,out,ls,task,learn,recall,steps,explain,gens,bank,examDesc,extra={})=>quick({id,o,ph,t,out,ls,task,learn,recall,steps,explain,gens,bank,examDesc,...extra});
common('m27',27,7,'ECHO X ORBIT: Two Engines & the Shared Rules','Know what the model is, the words in every call, and the three rules both engines share.',
 ['What ECHO X ORBIT is','Liquidity and the draw','The words: CISD, RB, OTE, 4H trend','Set up Confluence Master','The draw at least 2× the stop','Trade with the 4H trend'],
 'Set up Confluence Master (RB / iRB zones, FVGs and iFVGs, session highs and lows, true day open, HOD/LOD, EQH/EQL on 4H and daily, failure swings). Open the 4H chart before anything else and write down today\'s trend and the nearest draw.',
 [{t:'Two engines, one set of rules',h:`<p><b>ECHO X ORBIT</b> is the model behind the daily calls in the Discord: two engines that look for the same thing from different angles, a place where price is likely to turn <b>toward liquidity</b>. <b>Echo:</b> a sweep, a change in delivery (CISD), and a <b>rejection block inside a fair value gap</b>. <b>Orbit:</b> a <b>big swing</b>, a fib, a deep pullback into the <b>OTE zone</b>, and an inversion on the leg in. It has run at a <b>94% win rate</b> in FLOWMTD's backtest across five years of NQ data. The research stays private: what you learn is how the model thinks.</p>`},
  {t:'Liquidity and the draw',h:`<p>Stop losses sit just past obvious highs and lows, equal highs and lows, session highs and lows, and the previous day's high and low. That pool of orders is liquidity. Price running through it and snapping back is a <b>sweep</b>: step one for Echo, never an entry by itself. <b>The draw</b> is where price is heading next: your target.</p>`},
  {t:'The words in every call',h:tblx(['Word','Meaning'],[['FVG','Three candles where the 1st candle\'s high and the 3rd candle\'s low do not overlap'],['CISD','Change in State of Delivery: a close back through the open of the move that just ran'],['RB','Rejection Block: the wick area where price was rejected; in Echo it sits inside an FVG'],['OTE','Optimal Trade Entry: the 0.62–0.79 zone of a pullback'],['4H trend','Higher highs and lows (up) or lower highs and lows (down); ECHO X ORBIT trades with it']])},
  {t:'Rule 1: no draw, no trade',h:`<p>Every trade needs a draw on liquidity <b>at least 2× your stop</b> away. A 15-point stop needs a draw 30 points away. If every other box is ticked and the draw is only 16 points away, skip it: the draw is a requirement, not a confluence.</p>`},
  {t:'Rule 2: with the 4H trend',h:`<p>Open the 4H chart before anything else. Five years of backtesting said the same thing every way it was cut: the setups that pay are <b>with</b> the 4H trend. Piling on extra filters, like waiting for ES to agree, did not add to the edge. What did: the 4H trend, the true point of rejection, and an open draw. New York is the priority session, and near all-time highs the model works the same: stay with the trend, do not fade the high, and do not widen your stop.</p>`},
  {t:'The checklist',h:key('<p>With the 4H trend · engine identified (Echo or Orbit) · draw marked, at least 2× the stop · stop beyond the RB or the leg-in low, target fixed at the draw · under my daily cap, one trade at a time · no red-folder news in the next 15 minutes.</p>','Run it before every click')}],
 rc('Orders & Your First Trade','What is the first thing to know before any order?',['The dollars you will risk','How much you want to make','What others are doing','The news headline'],'Risk comes first, and in ECHO X ORBIT the draw must pay at least 2× it.'),
 [['<b>The two engines.</b>',tblx(['Engine','Pattern'],[['Echo','Sweep → CISD → rejection block inside the FVG'],['Orbit','Big swing → fib → OTE → inversion on the leg in']])],['<b>The 2× rule.</b>',tblx(['Stop','Minimum draw'],[['10 pts','20 pts'],['15 pts','30 pts'],['20 pts','40 pts']])]],
 {prompts:['Explain what ECHO X ORBIT is, the two engines, and what the shared rules are.','Explain the 2× rule and the 4H trend rule, and why you skip a clean setup that fails one of them.'],
  ideas:['Two engines: Echo (sweep, CISD, RB in an FVG) and Orbit (swing, fib, OTE, inversion)','Both look for a turn toward liquidity','A sweep alone is not an entry','The draw is your target, and must be at least 2× the stop away','No draw, no trade, even if everything else lines up','Trade with the 4H trend: counter-trend setups are where the edge leaks','Extra filters did not add to the edge: trend, true rejection and an open draw did','Size for the losing streak, not the average day']},
 [draw,minDraw,valid,engine],
 BANKS('ECHO X ORBIT',[
  ['Which engine trades a rejection block inside a fair value gap?',['Echo','Orbit','Both the same','Neither'],'Echo = sweep, CISD, RB in an FVG.'],
  ['Which engine uses a fib on a big swing?',['Orbit','Echo','Neither','Both'],'Orbit = big swing, fib, OTE, inversion on the leg in.'],
  ['What do both engines need before any entry?',['A draw on liquidity at least 2× the stop away','A news event','Three green candles','ES agreeing'],'No valid draw, no trade.'],
  ['Which chart sets the direction?',['The 4H trend','The 1m chart','ES','The daily only'],'Trade with the 4H trend.'],
  ['CISD is…',['A close back through the open of the move that just ran','Any big candle','A news event','A type of order'],'Proof delivery changed.'],
  ['Minimum draw for a 15-point stop?',['30 points','15 points','10 points','60 points'],'2× the stop.'],
  ['Counter-trend Echo against the 4H trend is…',['Lower quality: favour setups with the trend','Better: it catches the top','The same','Required'],'That is where the edge leaks away.'],
  ['Perfect setup, but no clear liquidity target in your direction.',['Skip it','Take it','Use a round number','Hold until it works'],'No draw, no trade.'],
  ['Near all-time highs the model…',['Works the same: stay with the trend, do not fade the high','Shorts the high','Widens the stop','Stops working'],'Nothing special happens there.'],
  ['Where do you read the CISD?',['By eye: Confluence Master does not mark it','Confluence Master marks it','From the Discord only','Not at all'],'The same goes for drawing the fib yourself.']]),
 'The two engines, the 2× rule, the 4H trend and valid-or-not decisions.');
common('m28',28,7,'Echo','Read and take an Echo: sweep, CISD, rejection block in the FVG.',
 ['How Echo works step by step','Finding the CISD and the rejection block','What makes a real rejection','Why Echo trades lose','Daily rules'],
 'On a past week in Bar Replay, find three Echo setups. For each mark the old low or high, the sweep, the FVG, the CISD line, the rejection block, the stop and the draw, and measure the draw against the stop.',
 [{t:'Step by step',h:`<ol><li><b>Liquidity</b> under an old low: stops sit just under it.</li><li><b>The sweep:</b> price dips under it, takes the stops, and the selling dries up. A sweep alone is not an entry.</li><li><b>Displacement and the FVG:</b> a strong candle rips back up and leaves a gap.</li><li><b>The CISD:</b> a candle closes above the open of the down-move that made the sweep.</li><li><b>The rejection block:</b> price comes back into the FVG and gets rejected, leaving a long wick. That wick is the Echo entry, taken with the 4H trend.</li><li><b>Entry, stop and draw:</b> stop just past the wick; target the next liquidity above, more than 2× the stop away.</li></ol>`},
  {t:'Build the narrative first',h:`<p>Before any Echo, decide which way you are allowed to trade and where it pays. Mark 1H and 4H fair value gaps, key opens (midnight, 6 PM, 8 PM, 10 AM, the new week opening gap) and liquidity pools. Pick the nearest unfilled draw in your direction: that is your target and bias. Never trade against your draw; if the draw is already hit, the trade is done; never short all-time highs. Below the 50% of the 1H range is discount (longs), above is premium (shorts).</p>`},
  {t:'A real rejection',h:`<p>Two things make a rejection block: a wick <b>sweeps</b> a level holding liquidity, and the candle <b>fails to close</b> beyond it. Even a one-point failure to close counts. A sweep of the high or low that <b>started</b> the range (external) beats a minor one inside it (internal). Every trade needs a gap behind it: the 4H and 1H are the narrative, the lower timeframes refine the entry. A CISD with no retest is just a close: you want price to come back, wick into the CISD level and fail to close through it. Once price closes through a level it is dead.</p>`},
  {t:'Why Echo trades lose',h:tblx(['Cause','Result'],[['No HTF gap behind it','The wick gets blown through'],['Untapped gap just past the level','Stopped, then it works'],['SMT sweep','NQ and ES run one high, then dump'],['A used level','Reacted earlier, fails now'],['Draw already taken','Valid entry, nowhere to go'],['Against the 4H trend','The biggest leak in the backtest'],['Forcing it in chop','No gaps, no trade']])+`<p>Name the cause after every losing trade.</p>`},
  {t:'Daily rules',h:`<p>A fixed daily cap: hit your loss cap and you are done; hit your trade cap and you are done; one trade at a time. Losing streaks are real in every year of the data: size so the worst streak cannot end your account. Write your rules down, skip a session when you feel off, and let alerts bring you to your levels.</p>`}],
 rc('ECHO X ORBIT: Two Engines & the Shared Rules','The minimum draw for a 15-point stop is…',['30 points','15 points','10 points','60 points'],'2× the stop.'),
 [['<b>Echo in order.</b>',tblx(['#','Step'],[['1','Sweep an old low'],['2','Displacement leaves an FVG'],['3','CISD: close above the open of the down-move'],['4','Return into the FVG: rejection block'],['5','Enter, stop past the wick, target the draw']])],['<b>Valid or not.</b>',tblx(['Case','Verdict'],[['RB just above the FVG, not inside','Not valid'],['Sweep but no CISD','Not an Echo'],['With the 4H trend, draw ≥ 2×','Valid'],['Level closed through earlier','Dead']])]],
 {prompts:['Walk through an Echo from the old low to the draw, and say what makes the rejection block real.','Give five reasons Echo trades lose and say how you avoid each.'],
  ideas:['Stops sit under an old low: that liquidity is taken first','A sweep alone is not an entry','Displacement leaves a fair value gap','CISD: a close back above the open of the down-move','The rejection block must be inside the FVG','External sweeps beat internal ones','Every trade needs a gap behind it and a retest of the CISD','Losses come from no HTF story, untapped gaps, SMT sweeps, used levels, a taken draw, counter-trend trades and forcing it']},
 [echoOrder,engine,valid,draw],
 BANKS('Echo',[
  ['Sweep, but price never closes back above the open of the down-move. Do you have an Echo?',['No: no CISD, no Echo','Yes','Only if ES agrees','Yes at half size'],'Without the CISD it is just a sweep that may keep going.'],
  ['An RB sits just above the FVG, not inside it. Valid Echo?',['No: it has to be inside the FVG','Yes, close enough','Only on Fridays','Yes with a wider stop'],'Inside the gap is the whole point.'],
  ['A wick sweeps the high but the candle closes one point back below it. A rejection?',['Yes: even a one-point failure to close counts','No: it needs 10 points','Only on the 4H','No'],'Sweep plus no close beyond equals rejection.'],
  ['Which is stronger?',['A sweep of the high that started the range (external)','A sweep of a minor high inside it (internal)','They are the same','Neither counts'],'External beats internal.'],
  ['A clean-looking wick with no gap or level behind it.',['Ignore it: random wicks get blown through','Take it','Take it with double size','Add to it'],'Only wicks rejecting out of a PD array with confluence.'],
  ['Price closed through your level earlier today. Use it again?',['No: a closed-through level is dead','Yes, as support now','Only on Fridays','Yes, once'],'No second life.'],
  ['You hit your daily loss cap, then a perfect setup forms.',['Done for the day','One more to win it back','Double size','Move the cap'],'Respect the cap.'],
  ['NQ runs the high and takes your stop while ES does not, then it dumps. That was…',['An SMT sweep','A breakout','News','A gap fill'],'Leave room for SMT sweeps at key highs and lows.'],
  ['Your draw was already hit. A new entry toward it is…',['Not valid: the trade is done','Fine','Better with size','A limit order'],'Confirm the draw is still open before every entry.']]),
 'Echo steps, what makes a valid rejection, and why Echo trades lose.',{});
common('m29',29,7,'Orbit','Map a pullback with a fib and enter only when the inversion confirms it.',
 ['How Orbit works step by step','Drawing the fib on a big swing','Waiting for the OTE zone','Confirmation, not anticipation','When Orbit works, and why Orbit trades lose'],
 'On a past week in Bar Replay, find three large moves that broke out of a long consolidation. Draw the fib from the swing low to the swing high, add 0.62 and 0.79, and note whether price reached OTE, what fresh gap formed on the leg in, and whether it inverted.',
 [{t:'Step by step',h:`<ol><li><b>Find the big swing:</b> a large, obvious move. Mark the swing low and the swing high. Small wiggles do not count.</li><li><b>Draw the fib</b> yourself (Confluence Master does not): 0 at the high, 1 at the low for a long.</li><li><b>The OTE zone:</b> the band between <b>0.62 and 0.79</b>. Orbit ignores shallow pullbacks and waits for price deep in it.</li><li><b>The leg in leaves a gap</b> on the way down.</li><li><b>Inversion:</b> price closes back above that gap. The pullback is done.</li><li><b>Entry</b> after the inversion, stop under the leg-in low, target the swing high's liquidity, at least 2× the stop away.</li></ol>`},
  {t:'A map, not a trigger',h:`<p>In the backtest, Orbit on its own was not where the edge came from. It tells you <b>where</b> a pullback should end. The trade comes when price reaches the zone, confirms, and it lines up with the <b>4H trend</b> and an open draw. The best area of interest is the deep pullback of a large move that broke out of a long consolidation and has not been retraced into yet. One area at a time.</p>`},
  {t:'Confirmation, not anticipation',h:`<p>Nothing happens until price actually reaches the zone: not near it, <b>into</b> it. Then you need a <b>fresh</b> gap formed out of the area closed through. Not an old gap, not one already inverted earlier, and ignore gaps in the <b>4 to 6 PM</b> close. If you have to adjust the drawing for it to line up, it is not the setup. Jumping the gun is the number one Orbit loss.</p>`},
  {t:'When it works, and why it loses',h:tblx(['Market','Orbit?'],[['Consolidation, two-sided','Yes: it shines'],['One-way expansion with no pullbacks','Rare: use Echo, OTE as confluence'],['Big news move','Wait for the deep pullback']])+tblx(['Cause of loss','Fix'],[['Jumping the gun','Wait until the zone is reached'],['Wrong anchors','Draw on the obvious big swing'],['Already-balanced swing','Anchor only to untapped swings'],['Stale or 4–6 PM gap','Use fresh gaps in session'],['Against the original play','Do not long bounces in a big down move'],['Draw already hit','Nowhere left to go']])+`<p>Trade slow: one trade a day if it sets up. A loss and a stop counts as a good day.</p>`}],
 rc('Echo','Echo enters at…',['A rejection block inside an FVG','The sweep','The CISD line','Any FVG'],'Orbit enters differently: after an inversion in the OTE zone.'),
 [['<b>Orbit in order.</b>',tblx(['#','Step'],[['1','Big swing'],['2','Fib: swing low to swing high'],['3','Price reaches 0.62–0.79'],['4','Gap on the leg in inverts'],['5','Enter, stop under the leg-in low']])],['<b>Valid or not.</b>',tblx(['Case','Verdict'],[['Pullback reaches only 0.38','Not Orbit'],['In OTE, nothing inverted','Wait'],['Fresh gap inverts inside the zone','Valid'],['Gap inverts at 5 PM','Ignore']])]],
 {prompts:['Walk through an Orbit from the big swing to the entry, and say why the inversion matters.','Explain why Orbit is a map and not a trigger, and when it works best.'],
  ideas:['Orbit starts with a large, obvious swing','You draw the fib yourself','OTE is the 0.62–0.79 band','Shallow pullbacks do not count: it must reach the zone','The leg in leaves a gap; its inversion says the pullback is done','Use only fresh gaps formed out of the zone, not old or 4 to 6 PM gaps','Orbit says where; the 4H trend and confirmation decide','It needs retracements: it shines in consolidating markets']},
 [orbitOrder,engine,valid,minDraw],
 BANKS('Orbit',[
  ['Orbit waits for price in…',['The OTE zone, 0.62–0.79','The 0.38 level','A new high','Any gap'],'The deep pullback.'],
  ['Orbit\'s confirmation on the leg in is…',['An inversion of the pullback\'s gap','A doji','Volume','A news candle'],'A close back through the gap.'],
  ['The pullback only reaches 0.38. Orbit?',['No: it has not reached OTE','Yes','Only with ES','Yes at half size'],'Orbit wants the deep pullback.'],
  ['Which swing do you draw the fib on?',['A big, clean, obvious swing','The last two candles','Any wiggle','The 1m noise'],'Small swings make meaningless fibs.'],
  ['Price is near the zone but has not reached it. A gap inverts. Enter?',['No: nothing counts until the zone is reached','Yes, close enough','Yes with a bigger stop','Yes at half size'],'Jumping the gun is the number one Orbit loss.'],
  ['Which gap counts?',['A fresh gap formed out of the zone','Any old gap','A gap that already inverted earlier','A gap from yesterday'],'Fresh gaps only.'],
  ['Orbit on its own is…',['A map of where a pullback should end, not a trigger','A buy signal','The whole model','Always right'],'Orbit says where; the confirmation and the trend decide.'],
  ['NQ has run straight up for weeks with barely a pullback. Orbit?',['Rarely: no retracements means no OTE entries','Perfect conditions','Only shorts','Every day'],'Orbit needs pullbacks.'],
  ['An OTE level is hit and price blows through with no inversion. That means…',['Your bias or range was wrong: zoom out and redraw','Add to the trade','Nothing','Double the size'],'No inversion, no trade.'],
  ['How many areas of interest at once?',['One','As many as you can draw','At least three','Ten'],'Several at once is looking for reasons to trade.']]),
 'Orbit steps, what counts as confirmation, and when Orbit works.',{});
common('m30',30,7,'ECHO X ORBIT: Make the Call (Final Exam)','Decide which setups to take and which to skip, then graduate.',
 ['Replays: one to take, one to skip','Running the checklist on every call','Reading Echo and Orbit together','Graduation: your certificate and the bot reward'],
 'Run the ECHO X ORBIT checklist on three real calls from the Discord. For each, say which engine it is, whether it is with the 4H trend, where the draw is, whether the draw is at least 2× the stop, and whether you would take it. Then check your answer against what price did.',
 [{t:'The decisions this module tests',h:`<p>Everything in the last three modules comes down to one choice on every call: <b>take it or skip it</b>. Run the checklist in order: <b>with the 4H trend?</b> Which engine? Is there a <b>draw at least 2× the stop</b>? Is the stop placed beyond the RB or the leg-in low, and the target fixed at the draw? Are you under your daily cap, with no red-folder news close? If any answer is no, it is a skip, however clean the pattern looks.</p>`},
  {t:'A short, taken',h:`<p>Price runs above an old high (a sweep, but not an entry yet). A big red candle then closes below the open of the up-move and leaves a gap: a CISD with an FVG. Price pushes back into the gap and leaves a long upper wick: the rejection block. The draw below is well over 2× the stop. Short from the RB, stop above it. Echo is the same story as the long, upside down.</p>`},
  {t:'A setup skipped',h:`<p>Sweep, CISD and an RB inside the FVG, all present. The only liquidity above is 16 points away against a 15-point stop. That is about 1× the stop, not 2×, so there is no valid draw: skip it. Skipping it was the trade.</p>`},
  {t:'What happens when you pass',h:`<p>Passing this module completes the school. You can download a certificate of completion and read how to claim the ECHO X ORBIT bot and private indicator: set up on a one-on-one Zoom call with Hannah. The school comes first because the bot runs the model, but you still need to know it: to check what it is doing, to know when not to run it, and to size for losing streaks.</p>`}],
 rc('Orbit','Orbit says where; what decides when?',['The confirmation and the 4H trend','The news','The 1m candle colour','ES'],'Orbit is a map, not a trigger.'),
 [['<b>The checklist.</b>',tblx(['Check','Required'],[['With the 4H trend','Yes'],['Engine identified','Echo or Orbit'],['Draw','At least 2× the stop'],['Stop and target','Stop past the RB or leg-in low; target at the draw'],['Daily cap and news','Under the cap; no news in 15 minutes']])]],
 {prompts:['Explain how you decide whether to take or skip an ECHO X ORBIT call, using the checklist in order.','Explain, with an example, a setup that looks perfect but must be skipped.'],
  ideas:['Check the 4H trend first','Identify the engine: Echo or Orbit','The draw must be at least 2× the stop away','A sweep alone is never the entry','Stop beyond the rejection block or the leg-in low; target fixed at the draw','Respect the daily cap and skip red-folder news','One missing box means skip, however clean the pattern','The bot runs the model; you still need to understand it']},
 [valid,echoOrder,orbitOrder,replay],
 BANKS('Make the call',[
  ['You exit at the draw and price runs another 100 points. You…',['Did it right: the target is fixed at the draw','Should have held','Should move targets further next time','Should add size'],'Many modest wins, not chasing runners.'],
  ['Which is a valid reason to skip a clean setup?',['The draw is under 2× the stop','It is Tuesday','The candle is red','The last trade won'],'No valid draw, no trade.'],
  ['ECHO X ORBIT is built to…',['Catch many modest wins at fixed draws','Catch every 100-point move','Trade every candle','Predict the news'],'The winners are bigger than the losers, and that adds up.'],
  ['How should you size?',['For the losing streak, not the average day','For the best day','For the news','All in'],'Losing streaks happen in every year of the data.'],
  ['Which engine does a big swing, a fib and an inversion describe?',['Orbit','Echo','Neither','Both'],'Orbit.'],
  ['A short Echo: where does the stop go?',['Above the rejection block','Below the draw','At the sweep low','Nowhere'],'Past the wick.'],
  ['When should you not run the bot?',['Around red-folder news','Never','On Fridays only','When you are winning'],'You still need to know when not to run it.'],
  ['What do you do if you cannot name the draw?',['Skip: no draw, no trade','Take it small','Use a round number','Wait for ES'],'The draw is required.']]),
 'Take-or-skip decisions on ECHO X ORBIT setups, ordering the engines and the checklist.',{});
})();
